NALMAGE: namespace._RDFNamespace Class Reference
namespace._RDFNamespace Class Reference
Public Member Functions
def __init__ (self)
def term (self, name)
Public Member Functions inherited from namespace.ClosedNamespace
def __getitem__ (self, key, default=None)
def __getattr__ (self, name)
def __str__ (self)
def __repr__ (self)
Additional Inherited Members
Data Fields inherited from namespace.ClosedNamespace
uri
Detailed Description
Closed namespace for RDF terms
Constructor & Destructor Documentation
__init__()
def namespace._RDFNamespace.__init__ (self)
Reimplemented from namespace.ClosedNamespace.
References namespace._RDFNamespace.__init__().
Referenced by namespace._RDFNamespace.__init__().
Member Function Documentation
term()
def namespace._RDFNamespace.term (self, name)
Reimplemented from namespace.ClosedNamespace.
References namespace._RDFNamespace.term(), and namespace.ClosedNamespace.uri.
Referenced by namespace.Namespace.__getattr__(), namespace.ClosedNamespace.__getattr__(), namespace.Namespace.__getitem__(), namespace.ClosedNamespace.__getitem__(), and namespace._RDFNamespace.term().
The documentation for this class was generated from the following file:
C:/Users/lt17550/University of Bristol/grp-Louis-Timperley-PhD - General/git-repos/thesis repos/NALMAGE_developement/pyDRAGONS/ontology-visualisation/namespace.py