NALMAGE: namespace.URIPattern Class Reference
namespace.URIPattern Class Reference
Public Member Functions
def __new__ (cls, value)
def __mod__ (self, *args, **kwargs)
def format (self, *args, **kwargs)
def __repr__ (self)
Member Function Documentation
__mod__()
def namespace.URIPattern.__mod__ (self, * args, ** kwargs)
References namespace.URIPattern.__mod__().
Referenced by namespace.URIPattern.__mod__().
__new__()
def namespace.URIPattern.__new__ (cls, value)
References namespace.URIPattern.__new__().
Referenced by namespace.URIPattern.__new__().
__repr__()
def namespace.URIPattern.__repr__ (self)
References namespace.URIPattern.__repr__().
Referenced by namespace.URIPattern.__repr__().
format()
def namespace.URIPattern.format (self, * args, ** kwargs)
References namespace.URIPattern.format().
Referenced by namespace.URIPattern.format().
The documentation for this class was generated from the following file:
C:/Users/lt17550/University of Bristol/grp-Louis-Timperley-PhD - General/git-repos/thesis repos/NALMAGE_developement/pyDRAGONS/ontology-visualisation/namespace.py