NALMAGE: sysml.system.Model Class Reference
sysml.system.Model Class Reference
Public Member Functions
None to_yaml (self, str filename)
def isValid (self)
Public Member Functions inherited from sysml.elements.structure.Package
def __init__ (self, Optional[str] name="", Optional[Union[Dict[str, "ModelElement"], List["ModelElement"]]] elements=None)
def __getitem__ (self, elementName)
def name (self)
def elements (self)
def add (self, element)
def remove (self, element)
def RTM (self)
Public Member Functions inherited from sysml.elements.base.ModelElement
def __repr__ (self)
def stereotype (self)
def uuid (self)
Detailed Description
This class defines a SysML system model. A system model serves as the
root namespace for subsuming all model elements (and relationships between
elements) of a system.
Member Function Documentation
isValid()
def sysml.system.Model.isValid (self)
Checks whether all requirements contained within model are satisfied
by a «block» and verified by a «testCase»
References sysml.system.Model.isValid().
Referenced by sysml.system.Model.isValid().
to_yaml()
None sysml.system.Model.to_yaml (self, str filename)
 Write this Project to a yaml file
References sysml.system.Model.to_yaml().
Referenced by sysml.system.Model.to_yaml().
The documentation for this class was generated from the following file:
C:/Users/lt17550/University of Bristol/grp-Louis-Timperley-PhD - General/git-repos/thesis repos/NALMAGE_developement/sysml/system.py