NALMAGE: pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Thing Class Reference
pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Thing Class Reference
Public Member Functions
def __init__ (self, name, *type)
def relationship (self, relationship_class, *args)
Data Fields
name
type
Constructor & Destructor Documentation
__init__()
def pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Thing.__init__ (self, name, * type)
References pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Thing.__init__().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Thing.__init__().
Member Function Documentation
relationship()
def pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Thing.relationship (self, relationship_class, * args)
References pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Thing.relationship().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Thing.relationship().
Field Documentation
name
pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Thing.name
Referenced by sysml.elements.parametrics.ValueType.__init__(), and sysml.elements.base.ModelElement.__repr__().
type
pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Thing.type
The documentation for this class was generated from the following file:
C:/Users/lt17550/University of Bristol/grp-Louis-Timperley-PhD - General/git-repos/thesis repos/NALMAGE_developement/pyDRAGONS/variability_framework_tools/variability_framework_textual_core.py