NALMAGE: pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules Class Reference
pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules Class Reference
Public Member Functions
def parse_rules (rules, framework_module)
def add_relevant_inverse (relationship, framework_module, obj, second, rule_list)
def resolve_types_inner (types, aliases)
def resolve_types (thing)
def allowed (action_to_test)
Static Public Attributes
list alias_list = []
list prohibition_list = []
list permission_list = []
list exclusive_list = []
Detailed Description
A class for parsing and applying rules in a rule-based system.
Attributes:
    alias_list (list): A list of type aliases.
    prohibition_list (list): A list of prohibited relationships.
    permission_list (list): A list of permitted relationships.
    exclusive_list (list): A list of exclusive relationships.
Methods:
    parse_rules(rules, framework_module):
        Parse and store rules.
    add_relevant_inverse(relationship, framework_module, obj, second, rule_list):
        Add relevant inverse relationships to the rule list.
    resolve_types_inner(types, aliases):
        Recursively resolve types based on aliases.
    resolve_types(thing):
        Resolve types for a given object.
    allowed(action_to_test):
        Check if an action is allowed based on rules.
Member Function Documentation
add_relevant_inverse()
def pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.add_relevant_inverse (relationship, framework_module, obj, second, rule_list)
Parse and store rules.
Args:
    rules (list): List of rule strings.
    framework_module: The framework module to identify relationships.
Returns:
    None
References pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.add_relevant_inverse(), pyDRAGONS.variability_framework_tools.variability_framework_textual_core.identify_relationship_class(), and pyDRAGONS.variability_framework_tools.variability_framework_textual_core.identify_relationship_class_from_name().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.add_relevant_inverse().
allowed()
def pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.allowed (action_to_test)
Check if an action is allowed based on rules.
Args:
    action_to_test: The action to test.
Returns:
    bool: True if the action is allowed, False otherwise.
References pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.allowed().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.allowed().
parse_rules()
def pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.parse_rules (rules, framework_module)
Parse and store rules.
Args:
    rules (list): List of rule strings.
    framework_module: The framework module to identify relationships.
Returns:
    None
References pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.parse_rules().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.parse_rules().
resolve_types()
def pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.resolve_types (thing)
Parse and store rules.
Args:
    rules (list): List of rule strings.
    framework_module: The framework module to identify relationships.
Returns:
    None
References pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.resolve_types().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.resolve_types().
resolve_types_inner()
def pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.resolve_types_inner (types, aliases)
Parse and store rules.
Args:
    rules (list): List of rule strings.
    framework_module: The framework module to identify relationships.
Returns:
    None
References pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.resolve_types_inner().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.resolve_types_inner().
Field Documentation
alias_list
list pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.alias_list = [] static
exclusive_list
list pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.exclusive_list = [] static
permission_list
list pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.permission_list = [] static
prohibition_list
list pyDRAGONS.variability_framework_tools.variability_framework_textual_core.Rules.prohibition_list = [] static
The documentation for this class was generated from the following file:
C:/Users/lt17550/University of Bristol/grp-Louis-Timperley-PhD - General/git-repos/thesis repos/NALMAGE_developement/pyDRAGONS/variability_framework_tools/variability_framework_textual_core.py