NALMAGE: pyDRAGONS.load_designs Namespace Reference
pyDRAGONS.load_designs Namespace Reference
Functions
def Load_designs (missions, do_comparison=True)
def main ()
Variables
graph = Graph("bolt://127.0.0.1:7687", auth=('neo4j', 'test'))
Graph database config.
Function Documentation
Load_designs()
def pyDRAGONS.load_designs.Load_designs (missions, do_comparison = True)
References pyDRAGONS.load_designs.Load_designs().
Referenced by pyDRAGONS.load_designs.Load_designs(), and pyDRAGONS.load_designs.main().
main()
def pyDRAGONS.load_designs.main ()
References pyDRAGONS.load_designs.Load_designs(), and pyDRAGONS.load_designs.main().
Referenced by pyDRAGONS.load_designs.main().
Variable Documentation
graph
pyDRAGONS.load_designs.graph = Graph("bolt://127.0.0.1:7687", auth=('neo4j', 'test'))
Graph database config.