NALMAGE: pyDRAGONS.variability_framework_tools.variability_framework_justifacation_testing Namespace Reference
pyDRAGONS.variability_framework_tools.variability_framework_justifacation_testing Namespace Reference
Functions
def test_edge_justification_against_framework (edge, variability_framework, graph)
def justify_design_against_framework (variability_framework, mission_name, design_name, graph)
Function Documentation
justify_design_against_framework()
def pyDRAGONS.variability_framework_tools.variability_framework_justifacation_testing.justify_design_against_framework (variability_framework, mission_name, design_name, graph)
References pyDRAGONS.variability_framework_tools.variability_framework_justifacation_testing.justify_design_against_framework().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_justifacation_testing.justify_design_against_framework().
test_edge_justification_against_framework()
def pyDRAGONS.variability_framework_tools.variability_framework_justifacation_testing.test_edge_justification_against_framework (edge, variability_framework, graph)
References pyDRAGONS.variability_framework_tools.variability_framework_justifacation_testing.test_edge_justification_against_framework().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_justifacation_testing.test_edge_justification_against_framework().