NALMAGE: pyDRAGONS.variability_framework_tools.rdf_conversion Namespace Reference
pyDRAGONS.variability_framework_tools.rdf_conversion Namespace Reference
Functions
def convert_to_rdf_class_orientated (rules, rdf_file_name)
def convert_to_rdf_relationship_orientated (rules, rdf_file_name)
Function Documentation
convert_to_rdf_class_orientated()
def pyDRAGONS.variability_framework_tools.rdf_conversion.convert_to_rdf_class_orientated (rules, rdf_file_name)
References pyDRAGONS.variability_framework_tools.rdf_conversion.convert_to_rdf_class_orientated().
Referenced by pyDRAGONS.variability_framework_tools.rdf_conversion.convert_to_rdf_class_orientated().
convert_to_rdf_relationship_orientated()
def pyDRAGONS.variability_framework_tools.rdf_conversion.convert_to_rdf_relationship_orientated (rules, rdf_file_name)
References pyDRAGONS.variability_framework_tools.rdf_conversion.convert_to_rdf_relationship_orientated().
Referenced by pyDRAGONS.variability_framework_tools.rdf_conversion.convert_to_rdf_relationship_orientated().