NALMAGE: pyDRAGONS.database_interaction.ontology_checking Namespace Reference
pyDRAGONS.database_interaction.ontology_checking Namespace Reference
Functions
def run_valid_neo_query (data, query, graph)
def create_valid_relationship (row, sourceType, targetKey, targetType, relationshipName, Ontology_Relationship, invalid_label_flag, invalid_relationship_label, leading_direction_character, post_direction_character, graph)
def process_valid_relationships (data, sourceType, targetKey, targetType, relationshipName, Ontology_Relationship, direction, graph)
Function Documentation
create_valid_relationship()
def pyDRAGONS.database_interaction.ontology_checking.create_valid_relationship (row, sourceType, targetKey, targetType, relationshipName, Ontology_Relationship, invalid_label_flag, invalid_relationship_label, leading_direction_character, post_direction_character, graph)
@brief Create valid relationships between nodes based on certain conditions.
This function creates relationships between nodes in a Neo4j graph database based on specified conditions.
It can also handle marking nodes as invalid when certain conditions are met.
@param row A dictionary containing data related to the relationship.
@param sourceType The type of the source node in the relationship.
@param targetKey The key used to identify the target node.
@param targetType The type of the target node in the relationship.
@param relationshipName The name of the relationship to be created.
@param Ontology_Relationship The name of the ontology relationship.
@param invalid_label_flag A flag indicating whether the invalid label exists.
@param invalid_relationship_label The label to be used for invalid relationships.
@param leading_direction_character The character for the leading direction in the relationship.
@param post_direction_character The character for the post direction in the relationship.
@param graph The Neo4j graph database instance.
@pre The input parameters should be properly formatted and consistent with the database schema.
@post The function will create relationships between nodes and may mark nodes as invalid based on conditions.
@see This function is useful for managing relationships and node validity in a Neo4j graph database.
References pyDRAGONS.database_interaction.ontology_checking.create_valid_relationship().
Referenced by pyDRAGONS.database_interaction.ontology_checking.create_valid_relationship(), and pyDRAGONS.database_interaction.ontology_checking.process_valid_relationships().
process_valid_relationships()
def pyDRAGONS.database_interaction.ontology_checking.process_valid_relationships (data, sourceType, targetKey, targetType, relationshipName, Ontology_Relationship, direction, graph)
@brief Process and create valid relationships between nodes based on specified conditions.
This function processes data and creates valid relationships between nodes in a Neo4j graph database based on specified conditions.
It also checks if relationships are allowed according to ontology rules.
@param data The data containing information about the relationships to be created.
@param sourceType The type of the source node in the relationship.
@param targetKey The key used to identify the target node.
@param targetType The type of the target node in the relationship.
@param relationshipName The name of the relationship to be created.
@param Ontology_Relationship The name of the ontology relationship.
@param direction The direction of the relationship (OUTGOING, INCOMING, or BOTH).
@param graph The Neo4j graph database instance.
@pre The input data should be properly formatted and consistent with the database schema.
@post The function will create valid relationships between nodes based on specified conditions.
@see This function is useful for processing and creating relationships in a Neo4j graph database while considering ontology rules.
References pyDRAGONS.database_interaction.ontology_checking.create_valid_relationship(), and pyDRAGONS.database_interaction.ontology_checking.process_valid_relationships().
Referenced by pyDRAGONS.database_interaction.ontology_checking.process_valid_relationships().
run_valid_neo_query()
def pyDRAGONS.database_interaction.ontology_checking.run_valid_neo_query (data, query, graph)
References pyDRAGONS.database_interaction.ontology_checking.run_valid_neo_query().
Referenced by pyDRAGONS.database_interaction.ontology_checking.run_valid_neo_query().