NALMAGE: pyDRAGONS.design_problem_formulation.random_design_generation Namespace Reference
pyDRAGONS.design_problem_formulation.random_design_generation Namespace Reference
Functions
def generate_design_element (name, dict labels, dict root_element_info, design_name, variability_framework, graph)
def generate_neighbours (allowed_neighbours, root_element, design_name, design_graph, variability_framework)
def generate_random_design (variability_framework, design_graph)
Function Documentation
generate_design_element()
def pyDRAGONS.design_problem_formulation.random_design_generation.generate_design_element (name, dict labels, dict root_element_info, design_name, variability_framework, graph)
References pyDRAGONS.design_problem_formulation.random_design_generation.generate_design_element().
Referenced by pyDRAGONS.design_problem_formulation.random_design_generation.generate_design_element(), pyDRAGONS.design_problem_formulation.random_design_generation.generate_neighbours(), and pyDRAGONS.design_problem_formulation.random_design_generation.generate_random_design().
generate_neighbours()
def pyDRAGONS.design_problem_formulation.random_design_generation.generate_neighbours (allowed_neighbours, root_element, design_name, design_graph, variability_framework)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools.check_for_relevant_type(), pyDRAGONS.design_problem_formulation.random_design_generation.generate_design_element(), pyDRAGONS.design_problem_formulation.random_design_generation.generate_neighbours(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools.identify_candidate_neighbours().
Referenced by pyDRAGONS.design_problem_formulation.random_design_generation.generate_neighbours(), and pyDRAGONS.design_problem_formulation.random_design_generation.generate_random_design().
generate_random_design()
def pyDRAGONS.design_problem_formulation.random_design_generation.generate_random_design (variability_framework, design_graph)
References pyDRAGONS.design_problem_formulation.random_design_generation.generate_design_element(), pyDRAGONS.design_problem_formulation.random_design_generation.generate_neighbours(), and pyDRAGONS.design_problem_formulation.random_design_generation.generate_random_design().
Referenced by pyDRAGONS.design_problem_formulation.random_design_generation.generate_random_design().