NALMAGE: main Namespace Reference
main Namespace Reference
Functions
def reset_transcript_file ()
def llm_based_design_process (design_data, design_name, mission_name, graph, variability_framework)
def main ()
Function Documentation
llm_based_design_process()
def main.llm_based_design_process (design_data, design_name, mission_name, graph, variability_framework)
References nalmage.model_generation.generate_elements(), nalmage.model_generation.generate_reduced_design_rule_set(), nalmage.model_generation.generate_relationships(), llm_based_design_process(), nalmage.ner_tools.logged_print(), nalmage.ner_tools.plogged_print(), nalmage.model_generation.prompt_llm_for_elements(), nalmage.model_generation.select_conversation(), nalmage.model_generation.select_element_generation_type(), and nalmage.model_generation.take_text_input().
Referenced by llm_based_design_process(), and main().
main()
def main.main ()
References pyDRAGONS.database_interaction.database_tools.clear_database(), llm_based_design_process(), pyDRAGONS.database_interaction.data_extraction.load_mission_requirements(), main(), pyDRAGONS.database_interaction.data_extraction.process_component_classifier_data(), pyDRAGONS.database_interaction.data_extraction.process_condition_classifier_data(), pyDRAGONS.database_interaction.data_extraction.process_design_data(), pyDRAGONS.database_interaction.data_extraction.process_function_classifier_data(), pyDRAGONS.database_interaction.data_extraction.process_mode_classifier_data(), pyDRAGONS.database_interaction.data_extraction.process_parameter_classifier_data(), pyDRAGONS.database_interaction.data_extraction.read_data(), and reset_transcript_file().
Referenced by main().
reset_transcript_file()
def main.reset_transcript_file ()
References nalmage.ner_tools.logged_print(), and reset_transcript_file().
Referenced by main(), and reset_transcript_file().