NALMAGE: nalmage.model_generation Namespace Reference
nalmage.model_generation Namespace Reference
Functions
def take_text_input (question)
def collect_all_component_functions (parent, child)
def collect_all_component_modes (parent, child)
def collect_all_component_mode_functions (parent, child, mode_name)
def collect_all_component_property_values (parent, child)
def completion_query (client, prompt, temperature)
def exchange (client, prompt, context)
def select_conversation (conversation, conversation_list)
def select_element_generation_type ()
def prompt_for_elements (client, prompt_input, conversation, down_selection)
def prompt_llm_for_elements (feedback_flag, client, conversation, generate_type, root_element, reduced_design_rules_string, reference_type, reference_element_string, query_returned_results, format_string)
def generate_elements (root_element, mission_name, element_list, selected_elements, design_data, design_name, super_types, reference_element_list, query_returned_results, graph, variability_framework)
def generate_relationships (design_variable, mission_name, element_list, selected_elements, design_data, design_name, query_returned_results, graph)
def generate_blocks (root_element, mission_name, element_list, selected_elements, design_data, design_name, graph, variability_framework)
def generate_value_properties (root_element, element_list, selected_elements)
def generate_modes (root_element, element_list, selected_elements)
def group_functions_into_modes (root_element, element_list, selected_elements)
def generate_functions (model, root_element, next_element, element_list, selected_elements)
def generate_capella_yaml_dec (parent, child, capella_model, output_file_name)
def generate_capella_pkg (parent, child, capella_parent_lc)
def generate_capella_lc (parent, child, capella_parent_lc)
def traverse_model_tree (model_section, capella_section)
def clean_capella_project (clean_project_name, working_project_name)
def run_capella_corrections ()
def convert_to_cappella_model (sysml_model, capella_model, output_file_name)
def manual_classifier_selection (element_name, candidate_classifiers)
def get_cosine (vec1, vec2)
def text_to_vector (text)
def cosine_simarlity_classifier_selection (element_name, candidate_classifiers)
def generate_reduced_design_rule_set (parent, variability_framework)
def classifier_selection (element_name, super_types, query_returned_results, variability_framework)
def reference_element_selection (reference_entry, design_data, mission_name, graph)
def interface_type_selection (reference_entry, grab_relationship_types)
def copy_and_squash_design_data (design_name, design_data)
Function Documentation
classifier_selection()
def nalmage.model_generation.classifier_selection (element_name, super_types, query_returned_results, variability_framework)
References nalmage.model_generation.classifier_selection(), and nalmage.model_generation.cosine_simarlity_classifier_selection().
Referenced by nalmage.model_generation.classifier_selection(), nalmage.model_generation.generate_blocks(), and nalmage.model_generation.generate_elements().
clean_capella_project()
def nalmage.model_generation.clean_capella_project (clean_project_name, working_project_name)
References nalmage.model_generation.clean_capella_project().
Referenced by nalmage.model_generation.clean_capella_project(), and nalmage.model_generation.convert_to_cappella_model().
collect_all_component_functions()
def nalmage.model_generation.collect_all_component_functions (parent, child)
References nalmage.model_generation.collect_all_component_functions(), and nalmage.ner_tools.logged_print().
Referenced by nalmage.model_generation.collect_all_component_functions().
collect_all_component_mode_functions()
def nalmage.model_generation.collect_all_component_mode_functions (parent, child, mode_name)
References nalmage.model_generation.collect_all_component_mode_functions(), and nalmage.ner_tools.logged_print().
Referenced by nalmage.model_generation.collect_all_component_mode_functions().
collect_all_component_modes()
def nalmage.model_generation.collect_all_component_modes (parent, child)
References nalmage.model_generation.collect_all_component_modes().
Referenced by nalmage.model_generation.collect_all_component_modes().
collect_all_component_property_values()
def nalmage.model_generation.collect_all_component_property_values (parent, child)
References nalmage.model_generation.collect_all_component_property_values().
Referenced by nalmage.model_generation.collect_all_component_property_values().
completion_query()
def nalmage.model_generation.completion_query (client, prompt, temperature)
References nalmage.model_generation.completion_query().
Referenced by nalmage.model_generation.completion_query(), and nalmage.model_generation.exchange().
convert_to_cappella_model()
def nalmage.model_generation.convert_to_cappella_model (sysml_model, capella_model, output_file_name)
References nalmage.model_generation.clean_capella_project(), nalmage.model_generation.convert_to_cappella_model(), nalmage.ner_tools.logged_print(), and nalmage.model_generation.traverse_model_tree().
Referenced by nalmage.model_generation.convert_to_cappella_model().
copy_and_squash_design_data()
def nalmage.model_generation.copy_and_squash_design_data (design_name, design_data)
References nalmage.model_generation.copy_and_squash_design_data().
Referenced by nalmage.model_generation.copy_and_squash_design_data().
cosine_simarlity_classifier_selection()
def nalmage.model_generation.cosine_simarlity_classifier_selection (element_name, candidate_classifiers)
References nalmage.model_generation.cosine_simarlity_classifier_selection(), nalmage.model_generation.get_cosine(), max(), and nalmage.model_generation.text_to_vector().
Referenced by nalmage.model_generation.classifier_selection(), nalmage.model_generation.cosine_simarlity_classifier_selection(), nalmage.model_generation.interface_type_selection(), nalmage.model_generation.prompt_llm_for_elements(), and nalmage.model_generation.reference_element_selection().
exchange()
def nalmage.model_generation.exchange (client, prompt, context)
References nalmage.model_generation.completion_query(), nalmage.model_generation.exchange(), and nalmage.ner_tools.logged_print().
Referenced by nalmage.model_generation.exchange(), nalmage.model_generation.prompt_for_elements(), and nalmage.model_generation.prompt_llm_for_elements().
generate_blocks()
def nalmage.model_generation.generate_blocks (root_element, mission_name, element_list, selected_elements, design_data, design_name, graph, variability_framework)
References nalmage.model_generation.classifier_selection(), and nalmage.model_generation.generate_blocks().
Referenced by nalmage.model_generation.generate_blocks().
generate_capella_lc()
def nalmage.model_generation.generate_capella_lc (parent, child, capella_parent_lc)
References nalmage.model_generation.generate_capella_lc(), and nalmage.ner_tools.logged_print().
Referenced by nalmage.model_generation.generate_capella_lc(), and nalmage.model_generation.traverse_model_tree().
generate_capella_pkg()
def nalmage.model_generation.generate_capella_pkg (parent, child, capella_parent_lc)
References nalmage.model_generation.generate_capella_pkg(), and nalmage.ner_tools.logged_print().
Referenced by nalmage.model_generation.generate_capella_pkg(), and nalmage.model_generation.traverse_model_tree().
generate_capella_yaml_dec()
def nalmage.model_generation.generate_capella_yaml_dec (parent, child, capella_model, output_file_name)
References nalmage.model_generation.generate_capella_yaml_dec(), and nalmage.ner_tools.logged_print().
Referenced by nalmage.model_generation.generate_capella_yaml_dec().
generate_elements()
def nalmage.model_generation.generate_elements (root_element, mission_name, element_list, selected_elements, design_data, design_name, super_types, reference_element_list, query_returned_results, graph, variability_framework)
References nalmage.model_generation.classifier_selection(), nalmage.model_generation.generate_elements(), and nalmage.model_generation.reference_element_selection().
Referenced by nalmage.model_generation.generate_elements(), and main.llm_based_design_process().
generate_functions()
def nalmage.model_generation.generate_functions (model, root_element, next_element, element_list, selected_elements)
References nalmage.model_generation.generate_functions(), and nalmage.ner_tools.logged_print().
Referenced by nalmage.model_generation.generate_functions().
generate_modes()
def nalmage.model_generation.generate_modes (root_element, element_list, selected_elements)
References nalmage.model_generation.generate_modes().
Referenced by nalmage.model_generation.generate_modes().
generate_reduced_design_rule_set()
def nalmage.model_generation.generate_reduced_design_rule_set (parent, variability_framework)
References nalmage.model_generation.generate_reduced_design_rule_set().
Referenced by nalmage.model_generation.generate_reduced_design_rule_set(), and main.llm_based_design_process().
generate_relationships()
def nalmage.model_generation.generate_relationships (design_variable, mission_name, element_list, selected_elements, design_data, design_name, query_returned_results, graph)
References nalmage.model_generation.generate_relationships(), nalmage.model_generation.interface_type_selection(), and nalmage.model_generation.reference_element_selection().
Referenced by nalmage.model_generation.generate_relationships(), and main.llm_based_design_process().
generate_value_properties()
def nalmage.model_generation.generate_value_properties (root_element, element_list, selected_elements)
References nalmage.model_generation.generate_value_properties().
Referenced by nalmage.model_generation.generate_value_properties().
get_cosine()
def nalmage.model_generation.get_cosine (vec1, vec2)
References nalmage.model_generation.get_cosine().
Referenced by nalmage.model_generation.cosine_simarlity_classifier_selection(), and nalmage.model_generation.get_cosine().
group_functions_into_modes()
def nalmage.model_generation.group_functions_into_modes (root_element, element_list, selected_elements)
References nalmage.model_generation.group_functions_into_modes(), nalmage.ner_tools.logged_print(), nalmage.ner_tools.plogged_print(), and nalmage.model_generation.take_text_input().
Referenced by nalmage.model_generation.group_functions_into_modes().
interface_type_selection()
def nalmage.model_generation.interface_type_selection (reference_entry, grab_relationship_types)
References nalmage.model_generation.cosine_simarlity_classifier_selection(), and nalmage.model_generation.interface_type_selection().
Referenced by nalmage.model_generation.generate_relationships(), and nalmage.model_generation.interface_type_selection().
manual_classifier_selection()
def nalmage.model_generation.manual_classifier_selection (element_name, candidate_classifiers)
References nalmage.ner_tools.logged_print(), nalmage.model_generation.manual_classifier_selection(), nalmage.ner_tools.plogged_print(), and nalmage.model_generation.take_text_input().
Referenced by nalmage.model_generation.manual_classifier_selection().
prompt_for_elements()
def nalmage.model_generation.prompt_for_elements (client, prompt_input, conversation, down_selection)
References nalmage.model_generation.exchange(), nalmage.ner_tools.identify_bulleted_list(), nalmage.ner_tools.identify_formatted_elements(), nalmage.ner_tools.identify_named_elements(), nalmage.ner_tools.logged_print(), nalmage.ner_tools.plogged_print(), nalmage.model_generation.prompt_for_elements(), and nalmage.model_generation.take_text_input().
Referenced by nalmage.model_generation.prompt_for_elements(), and nalmage.model_generation.prompt_llm_for_elements().
prompt_llm_for_elements()
def nalmage.model_generation.prompt_llm_for_elements (feedback_flag, client, conversation, generate_type, root_element, reduced_design_rules_string, reference_type, reference_element_string, query_returned_results, format_string)
References nalmage.model_generation.cosine_simarlity_classifier_selection(), nalmage.model_generation.exchange(), nalmage.ner_tools.identify_bulleted_list(), nalmage.ner_tools.identify_formatted_elements(), nalmage.ner_tools.logged_print(), nalmage.ner_tools.plogged_print(), nalmage.model_generation.prompt_for_elements(), nalmage.model_generation.prompt_llm_for_elements(), and nalmage.model_generation.take_text_input().
Referenced by main.llm_based_design_process(), and nalmage.model_generation.prompt_llm_for_elements().
reference_element_selection()
def nalmage.model_generation.reference_element_selection (reference_entry, design_data, mission_name, graph)
References nalmage.model_generation.cosine_simarlity_classifier_selection(), and nalmage.model_generation.reference_element_selection().
Referenced by nalmage.model_generation.generate_elements(), nalmage.model_generation.generate_relationships(), and nalmage.model_generation.reference_element_selection().
run_capella_corrections()
def nalmage.model_generation.run_capella_corrections ()
References nalmage.model_generation.run_capella_corrections().
Referenced by nalmage.model_generation.run_capella_corrections().
select_conversation()
def nalmage.model_generation.select_conversation (conversation, conversation_list)
References nalmage.ner_tools.logged_print(), nalmage.ner_tools.plogged_print(), nalmage.model_generation.select_conversation(), and nalmage.model_generation.take_text_input().
Referenced by main.llm_based_design_process(), and nalmage.model_generation.select_conversation().
select_element_generation_type()
def nalmage.model_generation.select_element_generation_type ()
References nalmage.ner_tools.logged_print(), nalmage.ner_tools.plogged_print(), nalmage.model_generation.select_element_generation_type(), and nalmage.model_generation.take_text_input().
Referenced by main.llm_based_design_process(), and nalmage.model_generation.select_element_generation_type().
take_text_input()
def nalmage.model_generation.take_text_input (question)
References nalmage.ner_tools.logged_print(), and nalmage.model_generation.take_text_input().
Referenced by nalmage.model_generation.group_functions_into_modes(), main.llm_based_design_process(), nalmage.model_generation.manual_classifier_selection(), nalmage.model_generation.prompt_for_elements(), nalmage.model_generation.prompt_llm_for_elements(), nalmage.model_generation.select_conversation(), nalmage.model_generation.select_element_generation_type(), and nalmage.model_generation.take_text_input().
text_to_vector()
def nalmage.model_generation.text_to_vector (text)
References nalmage.model_generation.text_to_vector().
Referenced by nalmage.model_generation.cosine_simarlity_classifier_selection(), and nalmage.model_generation.text_to_vector().
traverse_model_tree()
def nalmage.model_generation.traverse_model_tree (model_section, capella_section)
References nalmage.model_generation.generate_capella_lc(), nalmage.model_generation.generate_capella_pkg(), nalmage.ner_tools.logged_print(), and nalmage.model_generation.traverse_model_tree().
Referenced by nalmage.model_generation.convert_to_cappella_model(), and nalmage.model_generation.traverse_model_tree().