NALMAGE: pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing Namespace Reference
pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing Namespace Reference
Functions
def collect_perspective_against_framework (database_entry_type, grab_classifier, dict direction_flags_dict, graph)
This module provides tools for testing designs against a particular variability framework (or set of conditions) or identifying that variability framework.
def identify_element_type_from_mapping (node_tag, type_mapping)
def identify_relationship_class_from_mapping (relationship_tag, relationship_mapping, framework_module)
def test_edge_compliance_against_framework (edge, variability_framework)
def test_perspective_against_framework (database_entry_type, relationship_edges, thing_uid_list, thing_list, database_compliance, grab_classifier, mapping_module, variability_framework, graph)
def test_database_against_framework (labeled_types, thing_uid_list, thing_list, relationship_edges, database_compliance, mapping_module, variability_framework, controlled_flag, graph)
def test_compliance (mission_name, design_name, mapping_module, variability_framework, graph)
Function Documentation
collect_perspective_against_framework()
def pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.collect_perspective_against_framework (database_entry_type, grab_classifier, dict direction_flags_dict, graph)
This module provides tools for testing designs against a particular variability framework (or set of conditions) or identifying that variability framework.
References pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.collect_perspective_against_framework().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.collect_perspective_against_framework(), and pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_perspective_against_framework().
identify_element_type_from_mapping()
def pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.identify_element_type_from_mapping (node_tag, type_mapping)
References pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.identify_element_type_from_mapping().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.identify_element_type_from_mapping().
identify_relationship_class_from_mapping()
def pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.identify_relationship_class_from_mapping (relationship_tag, relationship_mapping, framework_module)
References pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.identify_relationship_class_from_mapping().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.identify_relationship_class_from_mapping().
test_compliance()
def pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_compliance (mission_name, design_name, mapping_module, variability_framework, graph)
References pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_compliance(), and pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_database_against_framework().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_compliance().
test_database_against_framework()
def pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_database_against_framework (labeled_types, thing_uid_list, thing_list, relationship_edges, database_compliance, mapping_module, variability_framework, controlled_flag, graph)
References pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_database_against_framework(), and pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_perspective_against_framework().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_compliance(), and pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_database_against_framework().
test_edge_compliance_against_framework()
def pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_edge_compliance_against_framework (edge, variability_framework)
References pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_edge_compliance_against_framework().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_edge_compliance_against_framework(), and pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_perspective_against_framework().
test_perspective_against_framework()
def pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_perspective_against_framework (database_entry_type, relationship_edges, thing_uid_list, thing_list, database_compliance, grab_classifier, mapping_module, variability_framework, graph)
References pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.collect_perspective_against_framework(), pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_edge_compliance_against_framework(), and pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_perspective_against_framework().
Referenced by pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_database_against_framework(), and pyDRAGONS.variability_framework_tools.variability_framework_compliance_testing.test_perspective_against_framework().