NALMAGE: pyDRAGONS.design_problem_formulation.product_line_engineering Namespace Reference
pyDRAGONS.design_problem_formulation.product_line_engineering Namespace Reference
Functions
def check_feautre_type (feature_name, variability_framework)
def list_requirement_names (graph)
def list_design_element_names (design_name, graph)
def list_existing_features (possible_secondary_types, design_name, graph)
def present_product_line_info (completed_query, design_name, mission_name, graph, variability_framework)
Function Documentation
check_feautre_type()
def pyDRAGONS.design_problem_formulation.product_line_engineering.check_feautre_type (feature_name, variability_framework)
References pyDRAGONS.design_problem_formulation.product_line_engineering.check_feautre_type().
Referenced by pyDRAGONS.design_problem_formulation.product_line_engineering.check_feautre_type().
list_design_element_names()
def pyDRAGONS.design_problem_formulation.product_line_engineering.list_design_element_names (design_name, graph)
References pyDRAGONS.design_problem_formulation.product_line_engineering.list_design_element_names().
Referenced by pyDRAGONS.design_problem_formulation.product_line_engineering.list_design_element_names().
list_existing_features()
def pyDRAGONS.design_problem_formulation.product_line_engineering.list_existing_features (possible_secondary_types, design_name, graph)
References pyDRAGONS.design_problem_formulation.product_line_engineering.list_existing_features().
Referenced by pyDRAGONS.design_problem_formulation.product_line_engineering.list_existing_features().
list_requirement_names()
def pyDRAGONS.design_problem_formulation.product_line_engineering.list_requirement_names (graph)
References pyDRAGONS.design_problem_formulation.product_line_engineering.list_requirement_names().
Referenced by pyDRAGONS.design_problem_formulation.product_line_engineering.list_requirement_names().
present_product_line_info()
def pyDRAGONS.design_problem_formulation.product_line_engineering.present_product_line_info (completed_query, design_name, mission_name, graph, variability_framework)
References pyDRAGONS.design_problem_formulation.product_line_engineering.present_product_line_info().
Referenced by pyDRAGONS.design_problem_formulation.product_line_engineering.present_product_line_info().