NALMAGE: pyDRAGONS.interface.interface Namespace Reference
pyDRAGONS.interface.interface Namespace Reference
Functions
def initialise ()
def display_processing_progress (root, task_name, progress)
def display_diagram_commands (root, missions_list)
def initialise_editor_explorer ()
def display_editor_commands (root, missions_list)
def json_tree (tree, parent, dictionary)
def show_query_data (data)
def secondary_feature_string_section (design_name, secondary_type)
def display_product_line (root, completed_query, design_name, mission_name, graph, variability_framework)
Function Documentation
display_diagram_commands()
def pyDRAGONS.interface.interface.display_diagram_commands (root, missions_list)
Display a GUI for generating diagram commands.
Args:
    root (tk.Tk): The root window of the GUI application.
    missions_list (dict): A dictionary containing missions and their associated designs.
Returns:
    None
References pyDRAGONS.interface.interface.display_diagram_commands().
Referenced by pyDRAGONS.interface.interface.display_diagram_commands().
display_editor_commands()
def pyDRAGONS.interface.interface.display_editor_commands (root, missions_list)
Display a GUI for generating diagram commands.
Args:
    root (tk.Tk): The root window of the GUI application.
    missions_list (dict): A dictionary containing missions and their associated designs.
Returns:
    None
References pyDRAGONS.interface.interface.display_editor_commands().
Referenced by pyDRAGONS.interface.interface.display_editor_commands().
display_processing_progress()
def pyDRAGONS.interface.interface.display_processing_progress (root, task_name, progress)
References pyDRAGONS.interface.interface.display_processing_progress().
Referenced by pyDRAGONS.interface.interface.display_processing_progress().
display_product_line()
def pyDRAGONS.interface.interface.display_product_line (root, completed_query, design_name, mission_name, graph, variability_framework)
References pyDRAGONS.interface.interface.display_product_line(), and pyDRAGONS.interface.interface.secondary_feature_string_section().
Referenced by pyDRAGONS.interface.interface.display_product_line().
initialise()
def pyDRAGONS.interface.interface.initialise ()
Initialize the GUI application.
Creates and configures the main GUI window with a specified title,
maximum size, and background color.
Returns:
    tk.Tk: The root window of the GUI application.
References pyDRAGONS.interface.interface.initialise().
Referenced by pyDRAGONS.interface.interface.initialise().
initialise_editor_explorer()
def pyDRAGONS.interface.interface.initialise_editor_explorer ()
Initialize the GUI application.
Creates and configures the editor GUI window with a specified title,
maximum size, and background color.
Returns:
    tk.Tk: The root window of the GUI application.
References pyDRAGONS.interface.interface.initialise_editor_explorer().
Referenced by pyDRAGONS.interface.interface.initialise_editor_explorer().
json_tree()
def pyDRAGONS.interface.interface.json_tree (tree, parent, dictionary)
References pyDRAGONS.interface.interface.json_tree().
Referenced by pyDRAGONS.interface.interface.json_tree(), and pyDRAGONS.interface.interface.show_query_data().
secondary_feature_string_section()
def pyDRAGONS.interface.interface.secondary_feature_string_section (design_name, secondary_type)
References pyDRAGONS.interface.interface.secondary_feature_string_section().
Referenced by pyDRAGONS.interface.interface.display_product_line(), and pyDRAGONS.interface.interface.secondary_feature_string_section().
show_query_data()
def pyDRAGONS.interface.interface.show_query_data (data)
References pyDRAGONS.interface.interface.json_tree(), and pyDRAGONS.interface.interface.show_query_data().
Referenced by pyDRAGONS.interface.interface.show_query_data().