NALMAGE: ontology_viz Namespace Reference
ontology_viz Namespace Reference
Data Structures
class OntologyGraph
Functions
def node_color (color)
def text_justify (words, max_width)
Variables
query_classes = prepareQuery(, initNs={'owl': OWL})
query_properties = prepareQuery(, initNs={'owl': OWL})
dictionary common_ns = {URIRef(ns) for ns in (RDF, RDFS, SKOS, SCHEMA, XSD, DOAP, FOAF)}
parser = argparse.ArgumentParser(description='Generate dot for the input ontology files')
nargs
help
dest
default
args = parser.parse_args()
config = Config(args.config)
og = OntologyGraph(args.files, config, args.format, ontology=args.ontology)
Function Documentation
node_color()
def ontology_viz.node_color (color)
References node_color().
Referenced by ontology_viz.OntologyGraph.convert(), and node_color().
text_justify()
def ontology_viz.text_justify (words, max_width)
References max(), and text_justify().
Referenced by ontology_viz.OntologyGraph.convert(), and text_justify().
Variable Documentation
args
ontology_viz.args = parser.parse_args()
common_ns
dictionary ontology_viz.common_ns = {URIRef(ns) for ns in (RDF, RDFS, SKOS, SCHEMA, XSD, DOAP, FOAF)}
config
ontology_viz.config = Config(args.config)
default
ontology_viz.default
dest
ontology_viz.dest
help
ontology_viz.help
nargs
ontology_viz.nargs
og
ontology_viz.og = OntologyGraph(args.files, config, args.format, ontology=args.ontology)
parser
ontology_viz.parser = argparse.ArgumentParser(description='Generate dot for the input ontology files')
query_classes
ontology_viz.query_classes = prepareQuery(, initNs={'owl': OWL})
query_properties
ontology_viz.query_properties = prepareQuery(, initNs={'owl': OWL})