NALMAGE: pyDRAGONS.test_result_viewer Namespace Reference
pyDRAGONS.test_result_viewer Namespace Reference
Functions
def load_current_set (path_to_json='test_results/')
def process_section_results (json_files, path_to_json)
def flatten (xss)
def select_result_files (path_to_res, group, select_list)
def take_dataframe_average_robust (dataframe_list)
def display_k_fold_results (path_to_res)
def scaling_study ()
def return_number_of_elements_in_design (design_name, graph)
def return_set_of_requirement_labels (mission_name, graph)
def main ()
Function Documentation
display_k_fold_results()
def pyDRAGONS.test_result_viewer.display_k_fold_results (path_to_res)
References pyDRAGONS.test_result_viewer.display_k_fold_results(), pyDRAGONS.test_result_viewer.flatten(), pyDRAGONS.test_result_viewer.process_section_results(), pyDRAGONS.test_result_viewer.select_result_files(), and pyDRAGONS.test_result_viewer.take_dataframe_average_robust().
Referenced by pyDRAGONS.test_result_viewer.display_k_fold_results(), pyDRAGONS.test_result_viewer.main(), and pyDRAGONS.test_result_viewer.scaling_study().
flatten()
def pyDRAGONS.test_result_viewer.flatten (xss)
References pyDRAGONS.test_result_viewer.flatten().
Referenced by pyDRAGONS.test_result_viewer.display_k_fold_results(), pyDRAGONS.test_result_viewer.flatten(), and pyDRAGONS.test_result_viewer.scaling_study().
load_current_set()
def pyDRAGONS.test_result_viewer.load_current_set (path_to_json = 'test_results/')
References pyDRAGONS.test_result_viewer.load_current_set().
Referenced by pyDRAGONS.test_result_viewer.load_current_set(), and pyDRAGONS.test_result_viewer.scaling_study().
main()
def pyDRAGONS.test_result_viewer.main ()
References pyDRAGONS.test_result_viewer.display_k_fold_results(), and pyDRAGONS.test_result_viewer.main().
Referenced by pyDRAGONS.test_result_viewer.main().
process_section_results()
def pyDRAGONS.test_result_viewer.process_section_results (json_files, path_to_json)
References pyDRAGONS.test_result_viewer.process_section_results().
Referenced by pyDRAGONS.test_result_viewer.display_k_fold_results(), pyDRAGONS.test_result_viewer.process_section_results(), and pyDRAGONS.test_result_viewer.scaling_study().
return_number_of_elements_in_design()
def pyDRAGONS.test_result_viewer.return_number_of_elements_in_design (design_name, graph)
References pyDRAGONS.test_result_viewer.return_number_of_elements_in_design().
Referenced by pyDRAGONS.test_result_viewer.return_number_of_elements_in_design(), and pyDRAGONS.test_result_viewer.scaling_study().
return_set_of_requirement_labels()
def pyDRAGONS.test_result_viewer.return_set_of_requirement_labels (mission_name, graph)
References pyDRAGONS.test_result_viewer.return_set_of_requirement_labels().
Referenced by pyDRAGONS.test_result_viewer.return_set_of_requirement_labels(), and pyDRAGONS.test_result_viewer.scaling_study().
scaling_study()
def pyDRAGONS.test_result_viewer.scaling_study ()
References pyDRAGONS.test_result_viewer.display_k_fold_results(), pyDRAGONS.test_result_viewer.flatten(), pyDRAGONS.test_result_viewer.load_current_set(), pyDRAGONS.test_result_viewer.process_section_results(), pyDRAGONS.test_result_viewer.return_number_of_elements_in_design(), pyDRAGONS.test_result_viewer.return_set_of_requirement_labels(), and pyDRAGONS.test_result_viewer.scaling_study().
Referenced by pyDRAGONS.test_result_viewer.scaling_study().
select_result_files()
def pyDRAGONS.test_result_viewer.select_result_files (path_to_res, group, select_list)
References pyDRAGONS.test_result_viewer.select_result_files().
Referenced by pyDRAGONS.test_result_viewer.display_k_fold_results(), and pyDRAGONS.test_result_viewer.select_result_files().
take_dataframe_average_robust()
def pyDRAGONS.test_result_viewer.take_dataframe_average_robust (dataframe_list)
References pyDRAGONS.test_result_viewer.take_dataframe_average_robust().
Referenced by pyDRAGONS.test_result_viewer.display_k_fold_results(), and pyDRAGONS.test_result_viewer.take_dataframe_average_robust().