NALMAGE: pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based Namespace Reference
pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based Namespace Reference
Functions
def identify_candidate_neighbours (root_type, variability_framework, bool include_superclass)
def identify_candidate_neighbours_class_orientated (root_type, variability_framework, bool include_superclass)
def identify_candidate_neighbours_relationship_orientated (root_type, variability_framework, bool include_superclass)
def process_uriref_string (uriref)
def check_for_relevant_type (labels, root_element_info)
def identify_super_classes (labels, variability_framework)
def identify_sub_classes (labels, subclass_list, variability_framework, debug)
def identify_child_types (labels, variability_framework, debug)
def test_if_specific (test_type, variability_framework, debug)
def identify_element_constraints (labels, variability_framework)
def categorize_neighbours (neighbours)
def filter_for_specific_types (candidate_neighbours, variability_framework)
def localise_context_to_design (catergorised_neighbours, root_local_element_uid, graph)
def design_context_framework_query (variability_framework, root_type, root_local_element_uid, filter_for_specific, graph)
def key_search (search_key, current_dict, location_key_set, discovered_element_list)
def per_context_additional_type_key_search (search_key, context_element, context_element_name, suggested_additional_model_elements)
def design_context_key_search (search_key, context, variability_framework)
def requirement_context_query (design_query, mission_name, variability_framework, graph)
def design_variable_context_query (design_query, design_name, variability_framework, graph)
def dependant_variable_context_query (design_query, design_name, variability_framework, graph)
def direct_variable_design_context_query (variable_type, design_query, design_name, variability_framework, graph)
def suggested_dependant_variables (design_variable_context, requirement_context, design_name, mission_name, variability_framework, graph)
def suggest_design_variables (design_variable_context, suggested_dependant_variable_context, requirement_context, design_name, mission_name, variability_framework, graph)
def suggest_requirements (design_variable_context, dependant_variable_context, design_name, variability_framework, graph)
def suggest_additional_design_model_elements (semi_completed_query, variability_framework)
def filter_additional_types (filtered_completed_query, select_types, section_key, variability_framework)
def select_relevant_additional_types (relevant_relationship_key, filtered_completed_query, variability_framework)
def design_context_query (variability_framework, dict design_query, mission_name, design_name, graph)
def categorize_neighbours_ontology_based (neighbours, query_ontology)
def design_context_framework_query_ontology_based (variability_framework, query_ontology, root_type, root_local_element_uid, filter_for_specific, graph)
def requirement_context_query_ontology_based (design_query, query_ontology, mission_name, variability_framework, graph)
def design_variable_context_query_ontology_based (design_query, design_name, variability_framework, query_ontology, graph)
def dependant_variable_context_query_ontology_based (design_query, design_name, variability_framework, query_ontology, graph)
def direct_variable_design_context_query_ontology_based (variable_type, design_query, design_name, variability_framework, query_ontology, graph)
def suggested_dependant_variables_ontology_based (design_variable_context, requirement_context, design_name, mission_name, variability_framework, query_ontology, graph)
def suggest_requirements_ontology_based (design_variable_context, dependant_variable_context, design_name, variability_framework, query_ontology, graph)
def design_query_via_ontology (variability_framework, query_ontology, dict design_query, mission_name, design_name, graph)
Function Documentation
categorize_neighbours()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.categorize_neighbours (neighbours)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.categorize_neighbours().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.categorize_neighbours(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query().
categorize_neighbours_ontology_based()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.categorize_neighbours_ontology_based (neighbours, query_ontology)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.categorize_neighbours_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.process_uriref_string().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.categorize_neighbours_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based().
check_for_relevant_type()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.check_for_relevant_type (labels, root_element_info)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.check_for_relevant_type().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.check_for_relevant_type(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types().
dependant_variable_context_query()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.dependant_variable_context_query (design_query, design_name, variability_framework, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.dependant_variable_context_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.dependant_variable_context_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query().
dependant_variable_context_query_ontology_based()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.dependant_variable_context_query_ontology_based (design_query, design_name, variability_framework, query_ontology, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.dependant_variable_context_query_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query_ontology_based().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.dependant_variable_context_query_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology().
design_context_framework_query()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query (variability_framework, root_type, root_local_element_uid, filter_for_specific, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.categorize_neighbours(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_for_specific_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.localise_context_to_design().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.requirement_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_requirements(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables().
design_context_framework_query_ontology_based()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based (variability_framework, query_ontology, root_type, root_local_element_uid, filter_for_specific, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.categorize_neighbours_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_for_specific_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.localise_context_to_design().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.requirement_context_query_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_requirements_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables_ontology_based().
design_context_key_search()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_key_search (search_key, context, variability_framework)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_key_search(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.per_context_additional_type_key_search().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_key_search(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_additional_design_model_elements().
design_context_query()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query (variability_framework, dict design_query, mission_name, design_name, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.dependant_variable_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_variable_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_additional_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.requirement_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.select_relevant_additional_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_additional_design_model_elements(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_design_variables(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_requirements(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query().
design_query_via_ontology()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology (variability_framework, query_ontology, dict design_query, mission_name, design_name, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.dependant_variable_context_query_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_variable_context_query_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_additional_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.process_uriref_string(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.requirement_context_query_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.select_relevant_additional_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_additional_design_model_elements(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_design_variables(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_requirements_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables_ontology_based().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology().
design_variable_context_query()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_variable_context_query (design_query, design_name, variability_framework, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_variable_context_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_variable_context_query().
design_variable_context_query_ontology_based()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_variable_context_query_ontology_based (design_query, design_name, variability_framework, query_ontology, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_variable_context_query_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query_ontology_based().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_variable_context_query_ontology_based().
direct_variable_design_context_query()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query (variable_type, design_query, design_name, variability_framework, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.dependant_variable_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_variable_context_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query().
direct_variable_design_context_query_ontology_based()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query_ontology_based (variable_type, design_query, design_name, variability_framework, query_ontology, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query_ontology_based().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.dependant_variable_context_query_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_variable_context_query_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.direct_variable_design_context_query_ontology_based().
filter_additional_types()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_additional_types (filtered_completed_query, select_types, section_key, variability_framework)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_additional_types(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_super_classes().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_additional_types().
filter_for_specific_types()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_for_specific_types (candidate_neighbours, variability_framework)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_for_specific_types(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_for_specific_types().
identify_candidate_neighbours()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours (root_type, variability_framework, bool include_superclass)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours_class_orientated().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours().
identify_candidate_neighbours_class_orientated()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours_class_orientated (root_type, variability_framework, bool include_superclass)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours_class_orientated(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.process_uriref_string().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours_class_orientated().
identify_candidate_neighbours_relationship_orientated()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours_relationship_orientated (root_type, variability_framework, bool include_superclass)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours_relationship_orientated(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.process_uriref_string().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours_relationship_orientated().
identify_child_types()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types (labels, variability_framework, debug)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.check_for_relevant_type(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_sub_classes(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_super_classes().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_key_search(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_for_specific_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.test_if_specific().
identify_element_constraints()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_element_constraints (labels, variability_framework)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_element_constraints(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.process_uriref_string().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_element_constraints().
identify_sub_classes()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_sub_classes (labels, subclass_list, variability_framework, debug)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_sub_classes(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.process_uriref_string().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_sub_classes().
identify_super_classes()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_super_classes (labels, variability_framework)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_super_classes(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.process_uriref_string().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.filter_additional_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_super_classes().
key_search()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.key_search (search_key, current_dict, location_key_set, discovered_element_list)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.key_search().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.key_search().
localise_context_to_design()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.localise_context_to_design (catergorised_neighbours, root_local_element_uid, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.localise_context_to_design().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.localise_context_to_design().
per_context_additional_type_key_search()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.per_context_additional_type_key_search (search_key, context_element, context_element_name, suggested_additional_model_elements)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.per_context_additional_type_key_search().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_key_search(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.per_context_additional_type_key_search().
process_uriref_string()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.process_uriref_string (uriref)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.process_uriref_string().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.categorize_neighbours_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours_class_orientated(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_candidate_neighbours_relationship_orientated(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_element_constraints(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_sub_classes(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_super_classes(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.process_uriref_string().
requirement_context_query()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.requirement_context_query (design_query, mission_name, variability_framework, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.requirement_context_query().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.requirement_context_query().
requirement_context_query_ontology_based()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.requirement_context_query_ontology_based (design_query, query_ontology, mission_name, variability_framework, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.requirement_context_query_ontology_based().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.requirement_context_query_ontology_based().
select_relevant_additional_types()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.select_relevant_additional_types (relevant_relationship_key, filtered_completed_query, variability_framework)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.select_relevant_additional_types(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.test_if_specific().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.select_relevant_additional_types().
suggest_additional_design_model_elements()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_additional_design_model_elements (semi_completed_query, variability_framework)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_key_search(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_additional_design_model_elements().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_additional_design_model_elements().
suggest_design_variables()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_design_variables (design_variable_context, suggested_dependant_variable_context, requirement_context, design_name, mission_name, variability_framework, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_design_variables().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_design_variables().
suggest_requirements()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_requirements (design_variable_context, dependant_variable_context, design_name, variability_framework, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_requirements().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_requirements().
suggest_requirements_ontology_based()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_requirements_ontology_based (design_variable_context, dependant_variable_context, design_name, variability_framework, query_ontology, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_requirements_ontology_based().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggest_requirements_ontology_based().
suggested_dependant_variables()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables (design_variable_context, requirement_context, design_name, mission_name, variability_framework, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.test_if_specific().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_query(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables().
suggested_dependant_variables_ontology_based()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables_ontology_based (design_variable_context, requirement_context, design_name, mission_name, variability_framework, query_ontology, graph)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_context_framework_query_ontology_based(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.test_if_specific().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.design_query_via_ontology(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables_ontology_based().
test_if_specific()
def pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.test_if_specific (test_type, variability_framework, debug)
References pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.identify_child_types(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.test_if_specific().
Referenced by pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.select_relevant_additional_types(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables(), pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.suggested_dependant_variables_ontology_based(), and pyDRAGONS.design_problem_formulation.design_problem_query_tools_ontology_based.test_if_specific().