NALMAGE: pyDRAGONS.database_interaction.data_extraction Namespace Reference
pyDRAGONS.database_interaction.data_extraction Namespace Reference
Functions
def read_data (name)
def generate_uid (data, type_tag)
def process_function_classifier_data (data, graph)
def process_component_classifier_data (data, graph)
def process_condition_classifier_data (data, graph)
def process_mode_classifier_data (data, graph)
def process_parameter_classifier_data (data, graph)
def process_design_data (mission_name, design_name, data, ontology_graph)
def process_satisfy_relationships (data, design_name, mission_name, graph)
def load_mission_requirements (mission_name, graph)
def load_complex_mission_requirements (mission_name, graph)
Function Documentation
generate_uid()
def pyDRAGONS.database_interaction.data_extraction.generate_uid (data, type_tag)
Generate unique identifiers (UIDs) and add them as a new column in a DataFrame.
This function takes a pandas DataFrame 'data' and a 'type_tag' as input. It generates
unique identifiers by combining the 'type_tag' and the 'name' column values (or others for
requirements and requirement clauses) for each row in the DataFrame. The UIDs are added
as a new 'uid' column in the DataFrame.
@param data: The input DataFrame containing at least a 'name' column.
@type data: pandas.DataFrame
@param type_tag: A string used as a prefix to create unique identifiers.
@type type_tag: str
@return: The input DataFrame with an additional 'uid' column containing the generated UIDs.
@rtype: pandas.DataFrame
@pre The 'data' DataFrame must contain a 'name' column.
@post The returned DataFrame will have an additional 'uid' column with unique identifiers.
@warning If the 'name' column does not exist in the input DataFrame, this function will raise
         a KeyError.
@see: You can use the pandas library for further DataFrame manipulation and analysis.
References pyDRAGONS.database_interaction.data_extraction.generate_uid().
Referenced by pyDRAGONS.database_interaction.data_extraction.generate_uid(), pyDRAGONS.database_interaction.data_extraction.load_complex_mission_requirements(), pyDRAGONS.database_interaction.data_extraction.load_mission_requirements(), pyDRAGONS.database_interaction.data_extraction.process_component_classifier_data(), pyDRAGONS.database_interaction.data_extraction.process_condition_classifier_data(), pyDRAGONS.database_interaction.data_extraction.process_design_data(), pyDRAGONS.database_interaction.data_extraction.process_function_classifier_data(), pyDRAGONS.database_interaction.data_extraction.process_mode_classifier_data(), and pyDRAGONS.database_interaction.data_extraction.process_parameter_classifier_data().
load_complex_mission_requirements()
def pyDRAGONS.database_interaction.data_extraction.load_complex_mission_requirements (mission_name, graph)
NOTE: NO LONGER USED
References pyDRAGONS.database_interaction.data_extraction.generate_uid(), and pyDRAGONS.database_interaction.data_extraction.load_complex_mission_requirements().
Referenced by pyDRAGONS.database_interaction.data_extraction.load_complex_mission_requirements().
load_mission_requirements()
def pyDRAGONS.database_interaction.data_extraction.load_mission_requirements (mission_name, graph)
Load mission requirements into a Neo4j graph database.
Parameters:
- mission_name (str): The name of the mission.
- graph: The Neo4j graph object to which the requirements will be loaded.
Returns:
None
This function reads mission requirements data from a file, processes it,
and loads it into the Neo4j graph database specified by the 'graph' parameter.
It performs the following steps:
1. Reads data from a file using the 'mission_name'.
2. Generates unique identifiers for the requirements.
3. Converts the data to a list of dictionaries for bulk insertion.
4. Executes a Cypher query to merge requirement nodes into the graph.
5. Adds domain labels to requirement nodes if domain information is provided.
Note:
- The function expects the 'graph' parameter to be a Neo4j graph object.
- The format of the mission requirements data file should be compatible
  with the processing steps defined in this function.
Example usage:
```
graph = neo4j.GraphDatabase.driver("bolt://localhost:7687")
load_mission_requirements("MissionX", graph)
```
References pyDRAGONS.database_interaction.data_extraction.generate_uid(), pyDRAGONS.database_interaction.data_extraction.load_mission_requirements(), and pyDRAGONS.database_interaction.data_extraction.read_data().
Referenced by pyDRAGONS.database_interaction.data_extraction.load_mission_requirements(), main.main(), and pyDRAGONS.design_editing.design_edit_tools.refresh_model_in_data_based().
process_component_classifier_data()
def pyDRAGONS.database_interaction.data_extraction.process_component_classifier_data (data, graph)
Process and insert component classifier data into a Neo4j graph database.
This function takes component classifier data in the form of a pandas DataFrame 'data'
and inserts it into a Neo4j graph database specified by the 'graph' parameter. The function
performs several data processing steps, including generating unique identifiers, filtering,
and formatting the data, and creating nodes and relationships in the graph.
@param data: The input DataFrame containing component classifier data.
@type data: pandas.DataFrame
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The component classifier data is inserted into the Neo4j graph database.
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References pyDRAGONS.database_interaction.data_extraction.generate_uid(), and pyDRAGONS.database_interaction.data_extraction.process_component_classifier_data().
Referenced by main.main(), and pyDRAGONS.database_interaction.data_extraction.process_component_classifier_data().
process_condition_classifier_data()
def pyDRAGONS.database_interaction.data_extraction.process_condition_classifier_data (data, graph)
Process and insert condition classifier data into a Neo4j graph database.
This function takes condition classifier data in the form of a pandas DataFrame 'data'
and inserts it into a Neo4j graph database specified by the 'graph' parameter. The function
performs several data processing steps, including generating unique identifiers, filtering,
and formatting the data, and creating nodes in the graph.
@param data: The input DataFrame containing condition classifier data.
@type data: pandas.DataFrame
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The condition classifier data is inserted into the Neo4j graph database.
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References pyDRAGONS.database_interaction.data_extraction.generate_uid(), and pyDRAGONS.database_interaction.data_extraction.process_condition_classifier_data().
Referenced by main.main(), and pyDRAGONS.database_interaction.data_extraction.process_condition_classifier_data().
process_design_data()
def pyDRAGONS.database_interaction.data_extraction.process_design_data (mission_name, design_name, data, ontology_graph)
Process and insert design data into a Neo4j graph database.
This function takes design data, represented as a pandas DataFrame 'data', and inserts it into a Neo4j
graph database specified by the 'ontology_graph' parameter. The function performs several data processing
steps, including generating unique identifiers, filtering, and formatting the data, and creating nodes and
relationships in the graph to represent design elements and their properties.
@param design_name: The name or identifier for the specific design instance being processed.
@type design_name: str
@param data: The input DataFrame containing design data.
@type data: pandas.DataFrame
@param ontology_graph: The Neo4j graph database connection for ontology data.
@type ontology_graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The design data is inserted into the Neo4j graph database with relationships to classifiers, children, and interfaces.
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References pyDRAGONS.database_interaction.data_extraction.generate_uid(), pyDRAGONS.database_interaction.data_extraction.process_design_data(), and pyDRAGONS.database_interaction.data_extraction.process_satisfy_relationships().
Referenced by main.main(), pyDRAGONS.database_interaction.data_extraction.process_design_data(), and pyDRAGONS.design_editing.design_edit_tools.refresh_model_in_data_based().
process_function_classifier_data()
def pyDRAGONS.database_interaction.data_extraction.process_function_classifier_data (data, graph)
Process and insert function classifier data into a Neo4j graph database.
This function takes function classifier data in the form of a pandas DataFrame 'data'
and inserts it into a Neo4j graph database specified by the 'graph' parameter. The function
performs several data processing steps, including generating unique identifiers, filtering,
and formatting the data, and creating nodes and relationships in the graph.
@param data: The input DataFrame containing function classifier data.
@type data: pandas.DataFrame
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The function classifier data is inserted into the Neo4j graph database.
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References pyDRAGONS.database_interaction.data_extraction.generate_uid(), and pyDRAGONS.database_interaction.data_extraction.process_function_classifier_data().
Referenced by main.main(), and pyDRAGONS.database_interaction.data_extraction.process_function_classifier_data().
process_mode_classifier_data()
def pyDRAGONS.database_interaction.data_extraction.process_mode_classifier_data (data, graph)
Process and insert mode classifier data into a Neo4j graph database.
This function takes mode classifier data in the form of a pandas DataFrame 'data'
and inserts it into a Neo4j graph database specified by the 'graph' parameter. The function
performs several data processing steps, including generating unique identifiers, filtering,
and formatting the data, and creating nodes and relationships in the graph.
@param data: The input DataFrame containing mode classifier data.
@type data: pandas.DataFrame
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The mode classifier data is inserted into the Neo4j graph database with relationships to allowed owners and conditions.
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References pyDRAGONS.database_interaction.data_extraction.generate_uid(), and pyDRAGONS.database_interaction.data_extraction.process_mode_classifier_data().
Referenced by main.main(), and pyDRAGONS.database_interaction.data_extraction.process_mode_classifier_data().
process_parameter_classifier_data()
def pyDRAGONS.database_interaction.data_extraction.process_parameter_classifier_data (data, graph)
Process and insert parameter classifier data into a Neo4j graph database.
This function takes parameter classifier data in the form of a pandas DataFrame 'data'
and inserts it into a Neo4j graph database specified by the 'graph' parameter. The function
performs several data processing steps, including generating unique identifiers, filtering,
and formatting the data, and creating nodes and relationships in the graph.
@param data: The input DataFrame containing parameter classifier data.
@type data: pandas.DataFrame
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The parameter classifier data is inserted into the Neo4j graph database with relationships to owners (Components, Subsystems, and Units).
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References pyDRAGONS.database_interaction.data_extraction.generate_uid(), and pyDRAGONS.database_interaction.data_extraction.process_parameter_classifier_data().
Referenced by main.main(), and pyDRAGONS.database_interaction.data_extraction.process_parameter_classifier_data().
process_satisfy_relationships()
def pyDRAGONS.database_interaction.data_extraction.process_satisfy_relationships (data, design_name, mission_name, graph)
Process satisfy relationships between design components and mission requirements.
Parameters:
- data (DataFrame): The data containing relationships between design components and requirements.
- design_name (str): The name of the design.
- mission_name (str): The name of the mission.
- graph: The Neo4j graph object representing the database.
Returns:
None
This function establishes direct 'satisfy' relationships between design components
and mission requirements in the Neo4j graph database.
It performs the following steps:
1. Defines the source and target node types for the relationship.
2. Specifies the key in the 'data' DataFrame containing requirement information.
3. Sets the relationship name to 'SATISFY'.
4. Calls a utility function to process the relationships and add them to the graph.
Note:
- The 'data' DataFrame is expected to contain the necessary information
  to establish the satisfy relationships.
- The 'graph' parameter should be a Neo4j graph object representing the database.
Example usage:
```
data = pd.DataFrame(...)  # Data containing relationship information
process_satisfy_relationships(data, "DesignA", "MissionX", graph)
```
References pyDRAGONS.database_interaction.data_extraction.process_satisfy_relationships().
Referenced by pyDRAGONS.database_interaction.data_extraction.process_design_data(), and pyDRAGONS.database_interaction.data_extraction.process_satisfy_relationships().
read_data()
def pyDRAGONS.database_interaction.data_extraction.read_data (name)
Read data from a CSV file and return it as a DataFrame.
This function reads a CSV file located in the './data/' directory with the
given 'name' and returns its contents as a pandas DataFrame.
@param name: The name of the CSV file (excluding the '.csv' extension).
@type name: str
@return: A pandas DataFrame containing the data from the CSV file.
@rtype: pandas.DataFrame
@pre The CSV file must exist in the './data/' directory.
@post The returned DataFrame will contain the data from the CSV file.
@warning If the specified CSV file does not exist, this function will raise
         a FileNotFoundError.
@see: You can use the pandas library for further data manipulation and analysis.
References pyDRAGONS.database_interaction.data_extraction.read_data().
Referenced by pyDRAGONS.database_interaction.data_extraction.load_mission_requirements(), main.main(), and pyDRAGONS.database_interaction.data_extraction.read_data().