NALMAGE: namespace Namespace Reference
namespace Namespace Reference
Data Structures
class _RDFNamespace
class ClosedNamespace
class Namespace
class NamespaceManager
class URIPattern
Functions
def is_ncname (name)
def split_uri (uri, split_start=SPLIT_START_CATEGORIES)
def insert_trie (trie, value)
def insert_strie (strie, trie, value)
def get_longest_namespace (trie, value)
Variables
RDF = _RDFNamespace()
RDFS
OWL = Namespace('http://www.w3.org/2002/07/owl#')
XSD = Namespace(_XSD_PFX)
SKOS = Namespace('http://www.w3.org/2004/02/skos/core#')
DOAP = Namespace('http://usefulinc.com/ns/doap#')
FOAF = Namespace('http://xmlns.com/foaf/0.1/')
DC = Namespace('http://purl.org/dc/elements/1.1/')
DCTERMS = Namespace('http://purl.org/dc/terms/')
VOID = Namespace('http://rdfs.org/ns/void#')
list NAME_START_CATEGORIES = ["Ll", "Lu", "Lo", "Lt", "Nl"]
list SPLIT_START_CATEGORIES = NAME_START_CATEGORIES + ['Nd']
list NAME_CATEGORIES = NAME_START_CATEGORIES + ["Mc", "Me", "Mn", "Lm", "Nd"]
list ALLOWED_NAME_CHARS = ["\u00B7", "\u0387", "-", ".", "_", ":"]
string XMLNS = "http://www.w3.org/XML/1998/namespace"
Function Documentation
get_longest_namespace()
def namespace.get_longest_namespace (trie, value)
References get_longest_namespace().
Referenced by namespace.NamespaceManager.compute_qname(), and get_longest_namespace().
insert_strie()
def namespace.insert_strie (strie, trie, value)
References insert_strie(), and insert_trie().
Referenced by namespace.NamespaceManager.compute_qname(), namespace.NamespaceManager.compute_qname_strict(), insert_strie(), and namespace.NamespaceManager.normalizeUri().
insert_trie()
def namespace.insert_trie (trie, value)
 Insert a value into the trie if it is not already contained in the trie.
    Return the subtree for the value regardless of whether it is a new value
    or not.
References insert_trie().
Referenced by namespace.NamespaceManager.bind(), insert_strie(), insert_trie(), and namespace.NamespaceManager.reset().
is_ncname()
def namespace.is_ncname (name)
References is_ncname().
Referenced by namespace.NamespaceManager.compute_qname_strict(), and is_ncname().
split_uri()
def namespace.split_uri (uri, split_start = SPLIT_START_CATEGORIES)
References format, and split_uri().
Referenced by ontology_viz.OntologyGraph.add_edge(), namespace.NamespaceManager.compute_qname(), namespace.NamespaceManager.compute_qname_strict(), namespace.NamespaceManager.normalizeUri(), and split_uri().
Variable Documentation
ALLOWED_NAME_CHARS
list namespace.ALLOWED_NAME_CHARS = ["\u00B7", "\u0387", "-", ".", "_", ":"]
DC
namespace.DC = Namespace('http://purl.org/dc/elements/1.1/')
DCTERMS
namespace.DCTERMS = Namespace('http://purl.org/dc/terms/')
DOAP
namespace.DOAP = Namespace('http://usefulinc.com/ns/doap#')
FOAF
namespace.FOAF = Namespace('http://xmlns.com/foaf/0.1/')
NAME_CATEGORIES
list namespace.NAME_CATEGORIES = NAME_START_CATEGORIES + ["Mc", "Me", "Mn", "Lm", "Nd"]
NAME_START_CATEGORIES
list namespace.NAME_START_CATEGORIES = ["Ll", "Lu", "Lo", "Lt", "Nl"]
OWL
namespace.OWL = Namespace('http://www.w3.org/2002/07/owl#')
RDF
namespace.RDF = _RDFNamespace()
RDFS
namespace.RDFS
Initial value:
=  ClosedNamespace(
    uri=URIRef("http://www.w3.org/2000/01/rdf-schema#"),
    terms=[
        "Resource", "Class", "subClassOf", "subPropertyOf", "comment", "label",
        "domain", "range", "seeAlso", "isDefinedBy", "Literal", "Container",
        "ContainerMembershipProperty", "member", "Datatype"]
)
SKOS
namespace.SKOS = Namespace('http://www.w3.org/2004/02/skos/core#')
SPLIT_START_CATEGORIES
list namespace.SPLIT_START_CATEGORIES = NAME_START_CATEGORIES + ['Nd']
VOID
namespace.VOID = Namespace('http://rdfs.org/ns/void#')
XMLNS
string namespace.XMLNS = "http://www.w3.org/XML/1998/namespace"
XSD
namespace.XSD = Namespace(_XSD_PFX)