NALMAGE: nalmage.ner_tools Namespace Reference
nalmage.ner_tools Namespace Reference
Functions
def identify_named_elements (completion)
def identify_bulleted_list (completion)
def remove_illegal_chars (str)
def identify_element_detail (element_text)
def identify_formatted_elements (element_text)
def output_model_to_yaml (model, model_file_name)
def import_model_from_yaml (model_file_name)
def logged_print (text)
def plogged_print (text)
Variables
string log_filename = 'transcript.txt'
Function Documentation
identify_bulleted_list()
def nalmage.ner_tools.identify_bulleted_list (completion)
References nalmage.ner_tools.identify_bulleted_list(), max(), and nalmage.ner_tools.remove_illegal_chars().
Referenced by nalmage.ner_tools.identify_bulleted_list(), nalmage.model_generation.prompt_for_elements(), and nalmage.model_generation.prompt_llm_for_elements().
identify_element_detail()
def nalmage.ner_tools.identify_element_detail (element_text)
References nalmage.ner_tools.identify_element_detail(), and max().
Referenced by nalmage.ner_tools.identify_element_detail().
identify_formatted_elements()
def nalmage.ner_tools.identify_formatted_elements (element_text)
References nalmage.ner_tools.identify_formatted_elements(), nalmage.ner_tools.logged_print(), and nalmage.ner_tools.remove_illegal_chars().
Referenced by nalmage.ner_tools.identify_formatted_elements(), nalmage.model_generation.prompt_for_elements(), and nalmage.model_generation.prompt_llm_for_elements().
identify_named_elements()
def nalmage.ner_tools.identify_named_elements (completion)
References nalmage.ner_tools.identify_named_elements(), and nalmage.ner_tools.logged_print().
Referenced by nalmage.ner_tools.identify_named_elements(), and nalmage.model_generation.prompt_for_elements().
import_model_from_yaml()
def nalmage.ner_tools.import_model_from_yaml (model_file_name)
References nalmage.diagram_generation.create_plantuml_diagram(), nalmage.ner_tools.import_model_from_yaml(), and nalmage.ner_tools.logged_print().
Referenced by nalmage.ner_tools.import_model_from_yaml().
logged_print()
def nalmage.ner_tools.logged_print (text)
References nalmage.ner_tools.logged_print().
Referenced by nalmage.model_generation.collect_all_component_functions(), nalmage.model_generation.collect_all_component_mode_functions(), nalmage.model_generation.convert_to_cappella_model(), nalmage.model_generation.exchange(), nalmage.model_generation.generate_capella_lc(), nalmage.model_generation.generate_capella_pkg(), nalmage.model_generation.generate_capella_yaml_dec(), nalmage.model_generation.generate_functions(), nalmage.model_generation.group_functions_into_modes(), nalmage.ner_tools.identify_formatted_elements(), nalmage.ner_tools.identify_named_elements(), nalmage.ner_tools.import_model_from_yaml(), main.llm_based_design_process(), nalmage.ner_tools.logged_print(), nalmage.model_generation.manual_classifier_selection(), nalmage.ner_tools.output_model_to_yaml(), nalmage.model_generation.prompt_for_elements(), nalmage.model_generation.prompt_llm_for_elements(), main.reset_transcript_file(), nalmage.model_generation.select_conversation(), nalmage.model_generation.select_element_generation_type(), nalmage.model_generation.take_text_input(), and nalmage.model_generation.traverse_model_tree().
output_model_to_yaml()
def nalmage.ner_tools.output_model_to_yaml (model, model_file_name)
References nalmage.diagram_generation.create_plantuml_diagram(), nalmage.ner_tools.logged_print(), and nalmage.ner_tools.output_model_to_yaml().
Referenced by nalmage.ner_tools.output_model_to_yaml().
plogged_print()
def nalmage.ner_tools.plogged_print (text)
References nalmage.ner_tools.plogged_print().
Referenced by nalmage.model_generation.group_functions_into_modes(), main.llm_based_design_process(), nalmage.model_generation.manual_classifier_selection(), nalmage.ner_tools.plogged_print(), nalmage.model_generation.prompt_for_elements(), nalmage.model_generation.prompt_llm_for_elements(), nalmage.model_generation.select_conversation(), and nalmage.model_generation.select_element_generation_type().
remove_illegal_chars()
def nalmage.ner_tools.remove_illegal_chars (str)
References nalmage.ner_tools.remove_illegal_chars().
Referenced by nalmage.ner_tools.identify_bulleted_list(), nalmage.ner_tools.identify_formatted_elements(), and nalmage.ner_tools.remove_illegal_chars().
Variable Documentation
log_filename
string nalmage.ner_tools.log_filename = 'transcript.txt'