NALMAGE: pyDRAGONS.graph_export.graph_export Namespace Reference
pyDRAGONS.graph_export.graph_export Namespace Reference
Functions
def export_design_to_edge_list (graph, design_name, file_name)
def export_query_subgraph_to_tikz (graph, query, colour_dict, file_name)
def export_comparison_to_edge_list (graph, mission_name, file_name)
def export_all_designs_to_edge_list (graph, missions_list)
Function Documentation
export_all_designs_to_edge_list()
def pyDRAGONS.graph_export.graph_export.export_all_designs_to_edge_list (graph, missions_list)
@brief Export all designs and comparisons from Neo4j graph database to edge list files.
This function exports all designs and their relationships in the specified missions, as well as comparisons
between designs, to edge list files for further analysis.
@param graph The Neo4j graph database connection.
@param missions_list A dictionary containing mission names as keys and lists of designs within each mission as values.
@return None
@pre 'graph' should be a valid Neo4j graph database connection.
@pre 'missions_list' should be a dictionary where keys are mission names, and values are lists of design names
     existing in the graph.
@see This function is useful for exporting designs and comparisons from a Neo4j graph database to edge list format,
     which can be used for various types of analysis.
References pyDRAGONS.graph_export.graph_export.export_all_designs_to_edge_list(), pyDRAGONS.graph_export.graph_export.export_comparison_to_edge_list(), and pyDRAGONS.graph_export.graph_export.export_design_to_edge_list().
Referenced by pyDRAGONS.graph_export.graph_export.export_all_designs_to_edge_list().
export_comparison_to_edge_list()
def pyDRAGONS.graph_export.graph_export.export_comparison_to_edge_list (graph, mission_name, file_name)
@brief Export comparisons from a Neo4j graph database to an edge list file.
This function executes Neo4j queries to retrieve comparisons and their relationships to differences and exports them
as an edge list to a text file.
@param graph The Neo4j graph database connection.
@param mission_name The name of the mission or comparison group.
@param file_name The name of the file to which the edge list will be exported.
@return None
@pre 'graph' should be a valid Neo4j graph database connection.
@pre 'mission_name' should be a valid mission or comparison group name existing in the graph.
@pre 'file_name' should be a valid file name.
@see This function is useful for exporting comparisons and their relationships from a Neo4j graph database
     to an edge list format, which can be used for further analysis.
References pyDRAGONS.graph_export.graph_export.export_comparison_to_edge_list().
Referenced by pyDRAGONS.graph_export.graph_export.export_all_designs_to_edge_list(), and pyDRAGONS.graph_export.graph_export.export_comparison_to_edge_list().
export_design_to_edge_list()
def pyDRAGONS.graph_export.graph_export.export_design_to_edge_list (graph, design_name, file_name)
@brief Export a specific design from a Neo4j graph database to an edge list file.
This function executes a Neo4j query to retrieve the edges of a specific design and exports them as an edge list
to a text file.
@param graph The Neo4j graph database connection.
@param design_name The name of the design to export.
@param file_name The name of the file to which the edge list will be exported.
@return None
@pre 'graph' should be a valid Neo4j graph database connection.
@pre 'design_name' should be a valid design name existing in the graph.
@pre 'file_name' should be a valid file name.
@see This function is useful for exporting the edges of a specific design from a Neo4j graph database
     to an edge list format, which can be used for further analysis.
References pyDRAGONS.graph_export.graph_export.export_design_to_edge_list().
Referenced by pyDRAGONS.graph_export.graph_export.export_all_designs_to_edge_list(), and pyDRAGONS.graph_export.graph_export.export_design_to_edge_list().
export_query_subgraph_to_tikz()
def pyDRAGONS.graph_export.graph_export.export_query_subgraph_to_tikz (graph, query, colour_dict, file_name)
@brief Export a specific design from a Neo4j graph database to an edge list file.
This function executes a Neo4j query to retrieve the edges of a specific design and exports them as an edge list
to a text file.
@param graph The Neo4j graph database connection.
@param design_name The name of the design to export.
@param file_name The name of the file to which the edge list will be exported.
@return None
@pre 'graph' should be a valid Neo4j graph database connection.
@pre 'design_name' should be a valid design name existing in the graph.
@pre 'file_name' should be a valid file name.
@see This function is useful for exporting the edges of a specific design from a Neo4j graph database
     to an edge list format, which can be used for further analysis.
References pyDRAGONS.graph_export.graph_export.export_query_subgraph_to_tikz().
Referenced by pyDRAGONS.graph_export.graph_export.export_query_subgraph_to_tikz().