NALMAGE: pyDRAGONS.graph_export.graph_plotting Namespace Reference
pyDRAGONS.graph_export.graph_plotting Namespace Reference
Functions
def display_association_rules (labeled_types, results)
def display_variability_framework_ontology (apriori_rules)
def traverse_comparison_tree (brief_name, comparisons_data, current_comparison, graph)
def generate_reduced_label (comparison_uid)
def acumulate_difference_counts (comparisons_data)
def plot_sankey (comparisons_data, plot_key)
def comparison_diff_count_sankey_diagrams (brief_name, graph)
def comparison_diff_count_icile_plots (comparisons_data)
def comparison_diff_count_pie_charts (comparisons_data)
Function Documentation
acumulate_difference_counts()
def pyDRAGONS.graph_export.graph_plotting.acumulate_difference_counts (comparisons_data)
@brief Accumulate difference counts for comparisons in a tree structure.
This function takes a comparisons data structure representing a tree of comparisons and their difference counts.
It accumulates the difference counts along the tree structure to compute cumulative difference counts.
@param comparisons_data A dictionary containing information about comparisons and their difference counts.
@return The updated comparisons_data dictionary with cumulative difference counts.
@pre The input 'comparisons_data' should be a valid dictionary structure representing comparisons and their difference counts.
@post The returned dictionary will include cumulative difference counts for the comparisons in the tree structure.
@see This function is useful for computing cumulative difference counts in a hierarchical structure of comparisons.
References pyDRAGONS.graph_export.graph_plotting.acumulate_difference_counts().
Referenced by pyDRAGONS.graph_export.graph_plotting.acumulate_difference_counts().
comparison_diff_count_icile_plots()
def pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_icile_plots (comparisons_data)
@brief Generate and display an Icicle Plot for difference counts in comparison data.
This function calculates and displays an Icicle Plot for difference counts in the given comparison data.
@param comparisons_data A dictionary containing information about the calculated difference counts and hierarchy.
@return The input dictionary containing the difference count information.
@pre The input 'comparisons_data' should be a dictionary with the required structure.
@post The function will display an Icicle Plot based on the provided difference count data.
@see This function is useful for visualizing the hierarchical structure of difference counts.
References pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_icile_plots().
Referenced by pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_icile_plots().
comparison_diff_count_pie_charts()
def pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_pie_charts (comparisons_data)
@brief Generate and display pie charts for difference counts related to comparison types.
This function calculates and displays two pie charts:
- One pie chart shows the number of differences related to each comparison type.
- Another pie chart shows the number of comparisons related to each comparison type.
@param comparisons_data A dictionary containing information about the calculated difference counts and hierarchy.
@return The input dictionary containing the difference count information.
@pre The input 'comparisons_data' should be a dictionary with the required structure.
@post The function will display two pie charts based on the provided data.
@see This function is useful for visualizing the distribution of differences and comparisons among comparison types.
References pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_pie_charts().
Referenced by pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_pie_charts().
comparison_diff_count_sankey_diagrams()
def pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_sankey_diagrams (brief_name, graph)
@brief Generate and display Sankey diagrams for difference counts in comparison data.
This function calculates and displays Sankey diagrams for difference counts in the given comparison data.
@param brief_name A string representing the brief name of the comparison data.
@param graph The Neo4j graph database containing the comparison data.
@return A dictionary containing information about the calculated difference counts and Sankey diagrams.
@pre The input 'brief_name' should be a valid string representing the comparison data.
@pre The input 'graph' should be a valid Neo4j graph database containing the comparison data.
@post The function will display Sankey diagrams based on difference counts and return a dictionary with related data.
@see This function is useful for visualizing the distribution of differences within comparison data.
References pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_sankey_diagrams(), pyDRAGONS.graph_export.graph_plotting.generate_reduced_label(), pyDRAGONS.graph_export.graph_plotting.plot_sankey(), and pyDRAGONS.graph_export.graph_plotting.traverse_comparison_tree().
Referenced by pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_sankey_diagrams().
display_association_rules()
def pyDRAGONS.graph_export.graph_plotting.display_association_rules (labeled_types, results)
@brief Display association rules graphically.
This function displays association rules graphically using a network graph visualization. It extracts data from
the given 'results' object, including rule support, confidence, and lift values, and plots the graph using Plotly
to visualize the association rules between items.
@param results A list of association rule results.
@return None
@pre 'results' should contain association rule results, typically obtained from association rule mining algorithms.
@see This function is useful for visually exploring and analyzing association rules between items in a dataset.
References pyDRAGONS.graph_export.graph_plotting.display_association_rules().
Referenced by pyDRAGONS.graph_export.graph_plotting.display_association_rules().
display_variability_framework_ontology()
def pyDRAGONS.graph_export.graph_plotting.display_variability_framework_ontology (apriori_rules)
@brief Display association rules graphically.
This function displays association rules graphically using a network graph visualization. It extracts data from
the given 'results' object, including rule support, confidence, and lift values, and plots the graph using Plotly
to visualize the association rules between items.
@param results A list of association rule results.
@return None
@pre 'results' should contain association rule results, typically obtained from association rule mining algorithms.
@see This function is useful for visually exploring and analyzing association rules between items in a dataset.
References pyDRAGONS.graph_export.graph_plotting.display_variability_framework_ontology().
Referenced by pyDRAGONS.graph_export.graph_plotting.display_variability_framework_ontology().
generate_reduced_label()
def pyDRAGONS.graph_export.graph_plotting.generate_reduced_label (comparison_uid)
@brief Generate a reduced label from a comparison UID.
This function takes a comparison UID, extracts the label information, and returns a reduced label. The reduced label
is typically used for visualization or formatting purposes.
@param comparison_uid The UID of the comparison, containing label information.
@return The reduced label extracted from the comparison UID.
@pre 'comparison_uid' should be a valid comparison UID with label information.
@see This function is useful for generating human-readable labels from comparison UIDs.
References pyDRAGONS.graph_export.graph_plotting.generate_reduced_label().
Referenced by pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_sankey_diagrams(), pyDRAGONS.graph_export.graph_plotting.generate_reduced_label(), and pyDRAGONS.graph_export.graph_plotting.traverse_comparison_tree().
plot_sankey()
def pyDRAGONS.graph_export.graph_plotting.plot_sankey (comparisons_data, plot_key)
@brief Plot a Sankey diagram based on the provided comparisons data.
This function generates a Sankey diagram from the given comparisons data using Plotly.
@param comparisons_data A dictionary containing information about comparisons and their links.
@param plot_key A string indicating the key within the comparisons_data dictionary to be used for plotting.
@pre The input 'comparisons_data' should be a valid dictionary structure representing comparisons and their links.
@pre The 'plot_key' should correspond to a valid key in 'comparisons_data'.
@post The function will display a Sankey diagram based on the specified 'plot_key'.
@see This function is useful for visualizing hierarchical relationships or flows represented in the comparisons data.
References pyDRAGONS.graph_export.graph_plotting.plot_sankey().
Referenced by pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_sankey_diagrams(), and pyDRAGONS.graph_export.graph_plotting.plot_sankey().
traverse_comparison_tree()
def pyDRAGONS.graph_export.graph_plotting.traverse_comparison_tree (brief_name, comparisons_data, current_comparison, graph)
@brief Traverse and analyze a comparison tree.
This function traverses a comparison tree structure, starting from the current comparison node, and collects data
about the comparisons and their relationships. It counts the number of differences for each comparison and
generates the necessary data structures for visualization.
@param brief_name The brief name or identifier for the comparisons.
@param comparisons_data A dictionary containing data structures for comparisons.
@param current_comparison The current comparison node to start the traversal.
@param graph The Neo4j graph database object for querying data.
@return The updated 'comparisons_data' dictionary with collected data.
@pre 'comparisons_data' should be initialized with appropriate data structures before calling this function.
@pre 'current_comparison' should be a valid comparison node in the database.
@pre 'graph' should be a valid Neo4j graph database connection.
@see This function is useful for analyzing and visualizing comparison trees, typically generated from a diff
     algorithm.
References pyDRAGONS.graph_export.graph_plotting.generate_reduced_label(), and pyDRAGONS.graph_export.graph_plotting.traverse_comparison_tree().
Referenced by pyDRAGONS.graph_export.graph_plotting.comparison_diff_count_sankey_diagrams(), and pyDRAGONS.graph_export.graph_plotting.traverse_comparison_tree().