NALMAGE: pyDRAGONS.variability_framework_testing Namespace Reference
pyDRAGONS.variability_framework_testing Namespace Reference
Functions
def list_names_of_element_type (requested_type, graph)
This module provides tools for testing collected differences against a particular variability framework (or set of conditions) or identifying that variability framework.
def filter_for_included_references (unfiltered_temp_data)
def correct_uid_and_type (temp_name, meta_type, graph)
def copy_over_labels (labels_response, temp_name, design_name, graph)
def grab_design_section (transaction_id, temp_name, design_name, meta_type, grab_relationship_type, root_element, graph)
def grab_design_section_dataframe_based (design_data, temp_data_unfiltered, mission_name, design_name, meta_type, grab_relationship_types, root_element, graph)
def return_types (meta_type, graph)
def calculate_precision_recall (grab_element_results, query_returned_results)
def aggregate_results (results)
def test_justification (transaction_id, meta_type, grab_relationship_types, temp_name, design_data, requirement_names, dependant_variable_names, step_type, root_element_name, results, mission_name, design_name, variability_framework, graph)
def test_llm_output (transaction_id, meta_type, grab_relationship_types, temp_name, design_data, requirement_names, dependant_variable_names, step_type, root_element_name, results, mission_name, design_name, variability_framework, graph)
def test_parameter_design_problems_in_design_non_func_reqs (temp_name, design_data, results, mission_name, design_name, variability_framework, graph)
def test_parameter_design_problems_in_design (transaction_id, meta_type, grab_relationship_types, temp_name, design_data, requirement_names, dependant_variable_names, step_type, root_element_name, results, mission_name, design_name, variability_framework, graph)
def test_justification_across_design (temp_name, design_name, mission_name, variability_framework, graph)
def test_llm_output_against_design (temp_name, design_name, mission_name, variability_framework, graph)
def K_fold_testing (missions)
def trigger_script (file_name)
def test_framework (missions)
def main ()
Function Documentation
aggregate_results()
def pyDRAGONS.variability_framework_testing.aggregate_results (results)
References pyDRAGONS.variability_framework_testing.aggregate_results().
Referenced by pyDRAGONS.variability_framework_testing.aggregate_results(), pyDRAGONS.variability_framework_testing.test_justification_across_design(), and pyDRAGONS.variability_framework_testing.test_llm_output_against_design().
calculate_precision_recall()
def pyDRAGONS.variability_framework_testing.calculate_precision_recall (grab_element_results, query_returned_results)
References pyDRAGONS.variability_framework_testing.calculate_precision_recall().
Referenced by pyDRAGONS.variability_framework_testing.calculate_precision_recall(), pyDRAGONS.variability_framework_testing.test_justification(), pyDRAGONS.variability_framework_testing.test_llm_output(), and pyDRAGONS.variability_framework_testing.test_parameter_design_problems_in_design().
copy_over_labels()
def pyDRAGONS.variability_framework_testing.copy_over_labels (labels_response, temp_name, design_name, graph)
References pyDRAGONS.variability_framework_testing.copy_over_labels().
Referenced by pyDRAGONS.variability_framework_testing.copy_over_labels(), and pyDRAGONS.variability_framework_testing.grab_design_section().
correct_uid_and_type()
def pyDRAGONS.variability_framework_testing.correct_uid_and_type (temp_name, meta_type, graph)
References pyDRAGONS.variability_framework_testing.correct_uid_and_type().
Referenced by pyDRAGONS.variability_framework_testing.correct_uid_and_type(), and pyDRAGONS.variability_framework_testing.grab_design_section().
filter_for_included_references()
def pyDRAGONS.variability_framework_testing.filter_for_included_references (unfiltered_temp_data)
References pyDRAGONS.variability_framework_testing.filter_for_included_references().
Referenced by pyDRAGONS.variability_framework_testing.filter_for_included_references(), and pyDRAGONS.variability_framework_testing.grab_design_section_dataframe_based().
grab_design_section()
def pyDRAGONS.variability_framework_testing.grab_design_section (transaction_id, temp_name, design_name, meta_type, grab_relationship_type, root_element, graph)
References pyDRAGONS.variability_framework_testing.copy_over_labels(), pyDRAGONS.variability_framework_testing.correct_uid_and_type(), and pyDRAGONS.variability_framework_testing.grab_design_section().
Referenced by pyDRAGONS.variability_framework_testing.grab_design_section(), pyDRAGONS.variability_framework_testing.test_justification(), pyDRAGONS.variability_framework_testing.test_justification_across_design(), pyDRAGONS.variability_framework_testing.test_llm_output(), and pyDRAGONS.variability_framework_testing.test_llm_output_against_design().
grab_design_section_dataframe_based()
def pyDRAGONS.variability_framework_testing.grab_design_section_dataframe_based (design_data, temp_data_unfiltered, mission_name, design_name, meta_type, grab_relationship_types, root_element, graph)
References pyDRAGONS.variability_framework_testing.filter_for_included_references(), pyDRAGONS.variability_framework_testing.grab_design_section_dataframe_based(), and pyDRAGONS.variability_framework_testing.return_types().
Referenced by pyDRAGONS.variability_framework_testing.grab_design_section_dataframe_based().
K_fold_testing()
def pyDRAGONS.variability_framework_testing.K_fold_testing (missions)
References pyDRAGONS.variability_framework_testing.K_fold_testing(), and pyDRAGONS.variability_framework_testing.test_framework().
Referenced by pyDRAGONS.variability_framework_testing.K_fold_testing().
list_names_of_element_type()
def pyDRAGONS.variability_framework_testing.list_names_of_element_type (requested_type, graph)
This module provides tools for testing collected differences against a particular variability framework (or set of conditions) or identifying that variability framework.
References pyDRAGONS.variability_framework_testing.list_names_of_element_type().
Referenced by pyDRAGONS.variability_framework_testing.list_names_of_element_type(), pyDRAGONS.variability_framework_testing.test_justification_across_design(), and pyDRAGONS.variability_framework_testing.test_llm_output_against_design().
main()
def pyDRAGONS.variability_framework_testing.main ()
References pyDRAGONS.variability_framework_testing.main(), and pyDRAGONS.variability_framework_testing.test_framework().
Referenced by pyDRAGONS.variability_framework_testing.main().
return_types()
def pyDRAGONS.variability_framework_testing.return_types (meta_type, graph)
References pyDRAGONS.variability_framework_testing.return_types().
Referenced by pyDRAGONS.variability_framework_testing.grab_design_section_dataframe_based(), and pyDRAGONS.variability_framework_testing.return_types().
test_framework()
def pyDRAGONS.variability_framework_testing.test_framework (missions)
References pyDRAGONS.variability_framework_testing.test_framework(), and pyDRAGONS.variability_framework_testing.test_justification_across_design().
Referenced by pyDRAGONS.variability_framework_testing.K_fold_testing(), pyDRAGONS.variability_framework_testing.main(), and pyDRAGONS.variability_framework_testing.test_framework().
test_justification()
def pyDRAGONS.variability_framework_testing.test_justification (transaction_id, meta_type, grab_relationship_types, temp_name, design_data, requirement_names, dependant_variable_names, step_type, root_element_name, results, mission_name, design_name, variability_framework, graph)
References pyDRAGONS.variability_framework_testing.calculate_precision_recall(), pyDRAGONS.variability_framework_testing.grab_design_section(), and pyDRAGONS.variability_framework_testing.test_justification().
Referenced by pyDRAGONS.variability_framework_testing.test_justification(), pyDRAGONS.variability_framework_testing.test_justification_across_design(), and pyDRAGONS.variability_framework_testing.test_llm_output_against_design().
test_justification_across_design()
def pyDRAGONS.variability_framework_testing.test_justification_across_design (temp_name, design_name, mission_name, variability_framework, graph)
References pyDRAGONS.variability_framework_testing.aggregate_results(), pyDRAGONS.variability_framework_testing.grab_design_section(), pyDRAGONS.variability_framework_testing.list_names_of_element_type(), pyDRAGONS.variability_framework_testing.test_justification(), pyDRAGONS.variability_framework_testing.test_justification_across_design(), and pyDRAGONS.variability_framework_testing.test_parameter_design_problems_in_design().
Referenced by pyDRAGONS.variability_framework_testing.test_framework(), and pyDRAGONS.variability_framework_testing.test_justification_across_design().
test_llm_output()
def pyDRAGONS.variability_framework_testing.test_llm_output (transaction_id, meta_type, grab_relationship_types, temp_name, design_data, requirement_names, dependant_variable_names, step_type, root_element_name, results, mission_name, design_name, variability_framework, graph)
References pyDRAGONS.variability_framework_testing.calculate_precision_recall(), pyDRAGONS.variability_framework_testing.grab_design_section(), and pyDRAGONS.variability_framework_testing.test_llm_output().
Referenced by pyDRAGONS.variability_framework_testing.test_llm_output().
test_llm_output_against_design()
def pyDRAGONS.variability_framework_testing.test_llm_output_against_design (temp_name, design_name, mission_name, variability_framework, graph)
References pyDRAGONS.variability_framework_testing.aggregate_results(), pyDRAGONS.variability_framework_testing.grab_design_section(), pyDRAGONS.variability_framework_testing.list_names_of_element_type(), pyDRAGONS.variability_framework_testing.test_justification(), and pyDRAGONS.variability_framework_testing.test_llm_output_against_design().
Referenced by pyDRAGONS.variability_framework_testing.test_llm_output_against_design().
test_parameter_design_problems_in_design()
def pyDRAGONS.variability_framework_testing.test_parameter_design_problems_in_design (transaction_id, meta_type, grab_relationship_types, temp_name, design_data, requirement_names, dependant_variable_names, step_type, root_element_name, results, mission_name, design_name, variability_framework, graph)
References pyDRAGONS.variability_framework_testing.calculate_precision_recall(), and pyDRAGONS.variability_framework_testing.test_parameter_design_problems_in_design().
Referenced by pyDRAGONS.variability_framework_testing.test_justification_across_design(), and pyDRAGONS.variability_framework_testing.test_parameter_design_problems_in_design().
test_parameter_design_problems_in_design_non_func_reqs()
def pyDRAGONS.variability_framework_testing.test_parameter_design_problems_in_design_non_func_reqs (temp_name, design_data, results, mission_name, design_name, variability_framework, graph)
References pyDRAGONS.variability_framework_testing.test_parameter_design_problems_in_design_non_func_reqs().
Referenced by pyDRAGONS.variability_framework_testing.test_parameter_design_problems_in_design_non_func_reqs().
trigger_script()
def pyDRAGONS.variability_framework_testing.trigger_script (file_name)
References pyDRAGONS.variability_framework_testing.trigger_script().
Referenced by pyDRAGONS.variability_framework_testing.trigger_script().