NALMAGE: pyDRAGONS.variability_framework_identifacation Namespace Reference
pyDRAGONS.variability_framework_identifacation Namespace Reference
Functions
def collect_perspective_against_framework (database_entry_type, grab_classifier, dict direction_flags_dict, graph)
This module provides tools for testing collected differences against a particular variability framework (or set of conditions) or identifying that variability framework.
def explore_database_perspective (database_entry_type, thing_uid_list, thing_list, relationship_edges, grab_classifier, graph)
def explore_difference_database (labeled_types, thing_uid_list, thing_list, relationship_edges, controlled_flag, graph)
def association_rule_mining_apriori (relationship_edges)
def convert_apriori_rules (labeled_types, apriori_results, self_relations_set)
def simplify_rules (rules)
def identify_type_hierarchy_via_relationship_rules_ (rules)
def catalogue_types_and_rules (rules)
def add_type_hierarchy_rules (types_list, rules)
def check_relationship_direction (rules, relationship_edges)
def identify_type_hierarchy (include_domains_flag, labeled_types, pure_labels, rules, graph)
def identify_type_hierarchy_via_coincident_labels (include_domains_flag, labeled_types, pure_labels, rules, graph)
def check_circular_hierarchy_on_rules (test_type, identifed_super_type_list, is_circular, rules)
def identify_labels (pure_labels, rules)
def identify_labels_auto (labeled_types, rules)
def identify_uniqueness_types (labeled_types, rules, graph)
def remove_uniqueness_rules (filter_statement, rules)
def write_relationship_class (framework_file, relationship_name)
def write_type_class (framework_file, type_name, parent)
def write_rules_to_framework_file (apriori_rules, filename)
def identify_product_line_features (labeled_types, string_rules, graph)
def identify_framework ()
def main ()
Variables
mapping_module = mapping_definition_1
Function Documentation
add_type_hierarchy_rules()
def pyDRAGONS.variability_framework_identifacation.add_type_hierarchy_rules (types_list, rules)
References pyDRAGONS.variability_framework_identifacation.add_type_hierarchy_rules().
Referenced by pyDRAGONS.variability_framework_identifacation.add_type_hierarchy_rules(), pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy_via_coincident_labels(), and pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy_via_relationship_rules_().
association_rule_mining_apriori()
def pyDRAGONS.variability_framework_identifacation.association_rule_mining_apriori (relationship_edges)
References pyDRAGONS.variability_framework_identifacation.association_rule_mining_apriori().
Referenced by pyDRAGONS.variability_framework_identifacation.association_rule_mining_apriori(), and pyDRAGONS.variability_framework_identifacation.identify_framework().
catalogue_types_and_rules()
def pyDRAGONS.variability_framework_identifacation.catalogue_types_and_rules (rules)
References pyDRAGONS.variability_framework_identifacation.catalogue_types_and_rules().
Referenced by pyDRAGONS.variability_framework_identifacation.catalogue_types_and_rules().
check_circular_hierarchy_on_rules()
def pyDRAGONS.variability_framework_identifacation.check_circular_hierarchy_on_rules (test_type, identifed_super_type_list, is_circular, rules)
References pyDRAGONS.variability_framework_identifacation.check_circular_hierarchy_on_rules().
Referenced by pyDRAGONS.variability_framework_identifacation.check_circular_hierarchy_on_rules(), and pyDRAGONS.variability_framework_identifacation.identify_labels_auto().
check_relationship_direction()
def pyDRAGONS.variability_framework_identifacation.check_relationship_direction (rules, relationship_edges)
References pyDRAGONS.variability_framework_identifacation.check_relationship_direction().
Referenced by pyDRAGONS.variability_framework_identifacation.check_relationship_direction(), and pyDRAGONS.variability_framework_identifacation.identify_framework().
collect_perspective_against_framework()
def pyDRAGONS.variability_framework_identifacation.collect_perspective_against_framework (database_entry_type, grab_classifier, dict direction_flags_dict, graph)
This module provides tools for testing collected differences against a particular variability framework (or set of conditions) or identifying that variability framework.
References pyDRAGONS.variability_framework_identifacation.collect_perspective_against_framework().
Referenced by pyDRAGONS.variability_framework_identifacation.collect_perspective_against_framework(), and pyDRAGONS.variability_framework_identifacation.explore_database_perspective().
convert_apriori_rules()
def pyDRAGONS.variability_framework_identifacation.convert_apriori_rules (labeled_types, apriori_results, self_relations_set)
References pyDRAGONS.variability_framework_identifacation.convert_apriori_rules().
Referenced by pyDRAGONS.variability_framework_identifacation.convert_apriori_rules(), and pyDRAGONS.variability_framework_identifacation.identify_framework().
explore_database_perspective()
def pyDRAGONS.variability_framework_identifacation.explore_database_perspective (database_entry_type, thing_uid_list, thing_list, relationship_edges, grab_classifier, graph)
References pyDRAGONS.variability_framework_identifacation.collect_perspective_against_framework(), and pyDRAGONS.variability_framework_identifacation.explore_database_perspective().
Referenced by pyDRAGONS.variability_framework_identifacation.explore_database_perspective(), and pyDRAGONS.variability_framework_identifacation.explore_difference_database().
explore_difference_database()
def pyDRAGONS.variability_framework_identifacation.explore_difference_database (labeled_types, thing_uid_list, thing_list, relationship_edges, controlled_flag, graph)
References pyDRAGONS.variability_framework_identifacation.explore_database_perspective(), and pyDRAGONS.variability_framework_identifacation.explore_difference_database().
Referenced by pyDRAGONS.variability_framework_identifacation.explore_difference_database(), and pyDRAGONS.variability_framework_identifacation.identify_framework().
identify_framework()
def pyDRAGONS.variability_framework_identifacation.identify_framework ()
References pyDRAGONS.variability_framework_identifacation.association_rule_mining_apriori(), pyDRAGONS.variability_framework_identifacation.check_relationship_direction(), pyDRAGONS.variability_framework_identifacation.convert_apriori_rules(), pyDRAGONS.variability_framework_identifacation.explore_difference_database(), pyDRAGONS.variability_framework_identifacation.identify_framework(), pyDRAGONS.variability_framework_identifacation.identify_product_line_features(), pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy(), and pyDRAGONS.variability_framework_identifacation.write_rules_to_framework_file().
Referenced by pyDRAGONS.variability_framework_identifacation.identify_framework(), and pyDRAGONS.variability_framework_identifacation.main().
identify_labels()
def pyDRAGONS.variability_framework_identifacation.identify_labels (pure_labels, rules)
References pyDRAGONS.variability_framework_identifacation.identify_labels().
Referenced by pyDRAGONS.variability_framework_identifacation.identify_labels().
identify_labels_auto()
def pyDRAGONS.variability_framework_identifacation.identify_labels_auto (labeled_types, rules)
References pyDRAGONS.variability_framework_identifacation.check_circular_hierarchy_on_rules(), and pyDRAGONS.variability_framework_identifacation.identify_labels_auto().
Referenced by pyDRAGONS.variability_framework_identifacation.identify_labels_auto().
identify_product_line_features()
def pyDRAGONS.variability_framework_identifacation.identify_product_line_features (labeled_types, string_rules, graph)
References pyDRAGONS.variability_framework_identifacation.identify_product_line_features().
Referenced by pyDRAGONS.variability_framework_identifacation.identify_framework(), and pyDRAGONS.variability_framework_identifacation.identify_product_line_features().
identify_type_hierarchy()
def pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy (include_domains_flag, labeled_types, pure_labels, rules, graph)
References pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy(), and pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy_via_coincident_labels().
Referenced by pyDRAGONS.variability_framework_identifacation.identify_framework(), and pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy().
identify_type_hierarchy_via_coincident_labels()
def pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy_via_coincident_labels (include_domains_flag, labeled_types, pure_labels, rules, graph)
References pyDRAGONS.variability_framework_identifacation.add_type_hierarchy_rules(), and pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy_via_coincident_labels().
Referenced by pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy(), and pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy_via_coincident_labels().
identify_type_hierarchy_via_relationship_rules_()
def pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy_via_relationship_rules_ (rules)
References pyDRAGONS.variability_framework_identifacation.add_type_hierarchy_rules(), pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy_via_relationship_rules_(), and max().
Referenced by pyDRAGONS.variability_framework_identifacation.identify_type_hierarchy_via_relationship_rules_().
identify_uniqueness_types()
def pyDRAGONS.variability_framework_identifacation.identify_uniqueness_types (labeled_types, rules, graph)
References pyDRAGONS.variability_framework_identifacation.identify_uniqueness_types().
Referenced by pyDRAGONS.variability_framework_identifacation.identify_uniqueness_types().
main()
def pyDRAGONS.variability_framework_identifacation.main ()
References pyDRAGONS.variability_framework_identifacation.identify_framework(), and pyDRAGONS.variability_framework_identifacation.main().
Referenced by pyDRAGONS.variability_framework_identifacation.main().
remove_uniqueness_rules()
def pyDRAGONS.variability_framework_identifacation.remove_uniqueness_rules (filter_statement, rules)
References pyDRAGONS.variability_framework_identifacation.remove_uniqueness_rules().
Referenced by pyDRAGONS.variability_framework_identifacation.remove_uniqueness_rules().
simplify_rules()
def pyDRAGONS.variability_framework_identifacation.simplify_rules (rules)
References pyDRAGONS.variability_framework_identifacation.simplify_rules().
Referenced by pyDRAGONS.variability_framework_identifacation.simplify_rules().
write_relationship_class()
def pyDRAGONS.variability_framework_identifacation.write_relationship_class (framework_file, relationship_name)
References pyDRAGONS.variability_framework_identifacation.write_relationship_class().
Referenced by pyDRAGONS.variability_framework_identifacation.write_relationship_class(), and pyDRAGONS.variability_framework_identifacation.write_rules_to_framework_file().
write_rules_to_framework_file()
def pyDRAGONS.variability_framework_identifacation.write_rules_to_framework_file (apriori_rules, filename)
References pyDRAGONS.variability_framework_identifacation.write_relationship_class(), pyDRAGONS.variability_framework_identifacation.write_rules_to_framework_file(), and pyDRAGONS.variability_framework_identifacation.write_type_class().
Referenced by pyDRAGONS.variability_framework_identifacation.identify_framework(), and pyDRAGONS.variability_framework_identifacation.write_rules_to_framework_file().
write_type_class()
def pyDRAGONS.variability_framework_identifacation.write_type_class (framework_file, type_name, parent)
References pyDRAGONS.variability_framework_identifacation.write_type_class().
Referenced by pyDRAGONS.variability_framework_identifacation.write_rules_to_framework_file(), and pyDRAGONS.variability_framework_identifacation.write_type_class().
Variable Documentation
mapping_module
pyDRAGONS.variability_framework_identifacation.mapping_module = mapping_definition_1