NALMAGE: pyDRAGONS.design_editing.design_edit_tools Namespace Reference
pyDRAGONS.design_editing.design_edit_tools Namespace Reference
Functions
def assign_type (element_name, candidate_type, design_data, design_name, classifier, component_data)
def add_interface (element_name, interface_type, source_element, design_data, design_name)
def edit_design_subclasses (design_name, component_data)
def list_requirements (mission_name, grab_text, graph)
def list_components (design_name, graph)
def list_functions (design_data)
def list_modes (design_data, mode_data)
def edit_design_functions (design_name, missions, mode_data, component_data)
def edit_data_file_function_details (label, design_data, function_data, function, design_name, colum_name, append_domain_suffix)
def add_inferred_assigment_labels (parameter_name, design_data, function_data, function_name, design_name, graph)
def infer_functional_assignments (design_name, function_data, graph)
def identify_spacecraft_name (design_data)
def add_element_ownership (element_name, parent_name, design_data, design_name)
def update_data_file_domains (Domain, data, req, mission_name)
def update_data_file_with_label (label, data, req, mission_name, colum_name)
def edit_mission_functional_requirements (mission_name, missions, graph)
def edit_mission_domains (mission_name, graph)
def list_domain_labels (mission_name)
def list_sub_class_labels (design_name)
def list_classifiers_of_type (classifier_data)
def list_design_elements (design_data)
def refresh_model_in_data_based (design_name, design_data, mission_name, graph)
Function Documentation
add_element_ownership()
def pyDRAGONS.design_editing.design_edit_tools.add_element_ownership (element_name, parent_name, design_data, design_name)
Add ownership of an element to a parent element in the design data.
Parameters:
- element_name (str): The name of the element to add ownership.
- parent_name (str): The name of the parent element.
- design_data (DataFrame): DataFrame containing design data.
- design_name (str): The name of the design.
Returns:
None
This function adds ownership of an element to a parent element in the design data.
It updates the 'children' column of the parent element with the name of the owned element.
It performs the following steps:
1. Updates the 'children' column of the parent element with the name of the owned element.
2. Writes the updated design data to the design file.
Note:
- The 'design_data' DataFrame should contain information about design elements.
- Both design data and ontology data are expected to be saved in the './data/' directory.
Example usage:
```
add_element_ownership("ElementX", "ParentElementY", design_data, "DesignA")
```
References pyDRAGONS.design_editing.design_edit_tools.add_element_ownership().
Referenced by pyDRAGONS.design_editing.design_edit_tools.add_element_ownership(), and pyDRAGONS.design_editing.design_edit_tools.edit_design_functions().
add_inferred_assigment_labels()
def pyDRAGONS.design_editing.design_edit_tools.add_inferred_assigment_labels (parameter_name, design_data, function_data, function_name, design_name, graph)
Add inferred assignment labels to related design parameters.
Parameters:
- parameter_name (str): The name of the parameter to add inferred assignment labels.
- design_data (DataFrame): DataFrame containing design data.
- function_data (DataFrame): DataFrame containing function data.
- function_name (str): The name of the function.
- design_name (str): The name of the design.
- graph: The Neo4j graph object representing the database.
Returns:
None
This function identifies parents of the related design parameter and adds inferred assignment labels
to them based on the provided function name and design data.
It performs the following steps:
1. Identifies the parents of the related design parameter.
2. Loops through the parents until there are no more parents.
3. Calls the 'edit_data_file_function_details' function to add inferred assignment labels to the parents.
4. Updates the design and function data files accordingly.
Note:
- The design data and function data are expected to be saved as CSV files.
- The 'parameter_name' parameter specifies the name of the parameter to add inferred assignment labels.
- The 'graph' parameter should be a Neo4j graph object representing the database.
- Both design data and ontology data are expected to be saved in the './data/' directory.
Example usage:
```
add_inferred_assigment_labels("ParameterX", design_data, function_data, "FunctionA", "DesignA", graph)
```
References pyDRAGONS.design_editing.design_edit_tools.add_inferred_assigment_labels(), and pyDRAGONS.design_editing.design_edit_tools.edit_data_file_function_details().
Referenced by pyDRAGONS.design_editing.design_edit_tools.add_inferred_assigment_labels(), and pyDRAGONS.design_editing.design_edit_tools.infer_functional_assignments().
add_interface()
def pyDRAGONS.design_editing.design_edit_tools.add_interface (element_name, interface_type, source_element, design_data, design_name)
References pyDRAGONS.design_editing.design_edit_tools.add_interface().
Referenced by pyDRAGONS.design_editing.design_edit_tools.add_interface().
assign_type()
def pyDRAGONS.design_editing.design_edit_tools.assign_type (element_name, candidate_type, design_data, design_name, classifier, component_data)
Assign a type to an element and update the ontology accordingly.
Parameters:
- element_name (str): The name of the element to assign the type to.
- candidate_type (str): The type to assign to the element.
- design_data (DataFrame): DataFrame containing design data.
- design_name (str): The name of the design.
- classifier (str): The classifier associated with the element.
- component_data (DataFrame): DataFrame containing component data.
Returns:
None
This function assigns a specified type to a given element and updates the associated design
data and ontology with the new type information.
It performs the following steps:
1. Checks if the 'sub_class' column exists in the design data, if not, adds it with 'NONE' values.
2. Assigns the candidate type to the element if it is not already assigned.
3. Updates the ontology with the allowed subtypes for the classifier.
4. Saves the updated design data and component data to CSV files.
Note:
- The 'design_data' DataFrame should contain information about design elements.
- The 'component_data' DataFrame should contain ontology information about components.
- Both 'design_data' and 'component_data' are expected to be saved as CSV files.
- The function updates the CSV files in the './data/' directory.
Example usage:
```
assign_type("ElementX", "TypeY", design_data, "DesignA", "ClassifierZ", component_data)
```
References pyDRAGONS.design_editing.design_edit_tools.assign_type().
Referenced by pyDRAGONS.design_editing.design_edit_tools.assign_type(), and pyDRAGONS.design_editing.design_edit_tools.edit_design_subclasses().
edit_data_file_function_details()
def pyDRAGONS.design_editing.design_edit_tools.edit_data_file_function_details (label, design_data, function_data, function, design_name, colum_name, append_domain_suffix)
Edit function details in design and ontology data files.
Parameters:
- label (str): The label to update.
- design_data (DataFrame): DataFrame containing design data.
- function_data (DataFrame): DataFrame containing function data.
- function (str): The name of the function to update.
- design_name (str): The name of the design.
- column_name (str): The name of the column to update.
- append_domain_suffix (bool): Whether to append domain suffix.
Returns:
None
This function updates function details in both design and ontology data files based on the provided label.
It performs the following steps:
1. Checks if the label is not 'NONE', 'Parameter', and not related to certain elements.
2. Modifies the label and updates the design and ontology data files accordingly.
3. Writes the updated design data to the design file.
4. Writes the updated ontology data to the ontology file.
Note:
- The design data and function data are expected to be saved as CSV files.
- The 'column_name' parameter specifies the column to update in both data files.
- Both design data and ontology data are expected to be saved in the './data/' directory.
Example usage:
```
edit_data_file_function_details("LabelA", design_data, function_data, "FunctionX", "DesignA", "ColumnA", True)
```
References pyDRAGONS.design_editing.design_edit_tools.edit_data_file_function_details().
Referenced by pyDRAGONS.design_editing.design_edit_tools.add_inferred_assigment_labels(), pyDRAGONS.design_editing.design_edit_tools.edit_data_file_function_details(), and pyDRAGONS.design_editing.design_edit_tools.infer_functional_assignments().
edit_design_functions()
def pyDRAGONS.design_editing.design_edit_tools.edit_design_functions (design_name, missions, mode_data, component_data)
Edit functions in a design based on mission requirements and mode data.
Parameters:
- design_name (str): The name of the design.
- missions (dict): A dictionary mapping mission names to their associated designs.
- mode_data (DataFrame): DataFrame containing mode information.
- component_data (DataFrame): DataFrame containing component data.
Returns:
None
This function allows for the editing of functions in a design based on mission requirements
and mode data. It adds new functions or links existing functions to requirements.
It performs the following steps:
1. Identifies the mission name associated with the design.
2. Reads design and requirement data from files using the provided names.
3. Iterates through each requirement and proposes new or existing functions based on functionality.
4. Adds new functions to the design if chosen by the user and updates the design data.
5. Identifies modes with no grouped function and generates notional functions for them.
6. Adds notional functions to the design and updates the design data.
Note:
- The design data is expected to be saved as a CSV file.
- The mission data should be a dictionary mapping mission names to associated designs.
- The mode data DataFrame should contain information about modes.
- The component data DataFrame should contain ontology information about components.
Example usage:
```
edit_design_functions("DesignA", missions, mode_data, component_data)
```
References pyDRAGONS.design_editing.design_edit_tools.add_element_ownership(), pyDRAGONS.design_editing.design_edit_tools.edit_design_functions(), pyDRAGONS.design_editing.design_edit_tools.identify_spacecraft_name(), pyDRAGONS.design_editing.design_edit_tools.list_functions(), and pyDRAGONS.design_editing.design_edit_tools.list_modes().
Referenced by pyDRAGONS.design_editing.design_edit_tools.edit_design_functions().
edit_design_subclasses()
def pyDRAGONS.design_editing.design_edit_tools.edit_design_subclasses (design_name, component_data)
Edit subclasses of elements in a design and update the ontology.
Parameters:
- design_name (str): The name of the design.
- component_data (DataFrame): DataFrame containing ontology information about components.
Returns:
None
This function allows for the editing of subclasses of elements in a design and updates
the associated design data and ontology accordingly.
It performs the following steps:
1. Reads design data from a file using the provided design name.
2. Iterates over each element in the design data.
3. Identifies candidate types based on element names and classifiers.
4. Prompts the user to accept the candidate type, suggest an alternative, or avoid.
5. Calls the 'assign_type' function to assign or suggest the type and update the ontology.
6. Prints the updated design data.
Note:
- The design data is expected to be saved as a CSV file.
- The component data DataFrame should contain ontology information about components.
- Both design data and component data are expected to be saved in the './data/' directory.
Example usage:
```
edit_design_subclasses("DesignA", component_data)
```
References pyDRAGONS.design_editing.design_edit_tools.assign_type(), and pyDRAGONS.design_editing.design_edit_tools.edit_design_subclasses().
Referenced by pyDRAGONS.design_editing.design_edit_tools.edit_design_subclasses().
edit_mission_domains()
def pyDRAGONS.design_editing.design_edit_tools.edit_mission_domains (mission_name, graph)
Edit domains of requirements for a mission.
Parameters:
- mission_name (str): The name of the mission.
- graph: The Neo4j graph object representing the database.
Returns:
None
This function allows for the editing of domains of requirements for a mission.
It reads mission data from a file and iterates through each requirement,
prompting the user to suggest domain labels.
It performs the following steps:
1. Reads mission data from the provided mission name.
2. Iterates through each requirement and prompts the user to suggest domain labels.
3. Updates the database with the suggested domain labels for each requirement.
4. Updates the data file with the corresponding domain labels.
Note:
- The mission data is expected to be saved in a file named '{mission_name}_Info.csv'.
- The 'graph' parameter should be a Neo4j graph object representing the database.
Example usage:
```
edit_mission_domains("MissionA", graph)
```
References pyDRAGONS.design_editing.design_edit_tools.edit_mission_domains(), and pyDRAGONS.design_editing.design_edit_tools.update_data_file_domains().
Referenced by pyDRAGONS.design_editing.design_edit_tools.edit_mission_domains().
edit_mission_functional_requirements()
def pyDRAGONS.design_editing.design_edit_tools.edit_mission_functional_requirements (mission_name, missions, graph)
Edit functional requirements of a mission.
Parameters:
- mission_name (str): The name of the mission.
- missions (dict): A dictionary mapping mission names to their associated designs.
- graph: The Neo4j graph object representing the database.
Returns:
None
This function allows for the editing of functional requirements of a mission.
It reads mission data from a file and iterates through each requirement,
prompting the user to label it as functional or non-functional.
It performs the following steps:
1. Reads mission data from the provided mission name.
2. Iterates through each requirement and prompts the user to label it as functional or non-functional.
3. Updates the database with the functional label for each requirement.
4. Updates the data file with the corresponding functional/non-functional label.
Note:
- The mission data is expected to be saved in a file named '{mission_name}_info.csv'.
- The 'missions' dictionary should contain mappings of mission names to associated designs.
- The 'graph' parameter should be a Neo4j graph object representing the database.
Example usage:
```
edit_mission_functional_requirements("MissionA", missions, graph)
```
References pyDRAGONS.design_editing.design_edit_tools.edit_mission_functional_requirements(), and pyDRAGONS.design_editing.design_edit_tools.update_data_file_with_label().
Referenced by pyDRAGONS.design_editing.design_edit_tools.edit_mission_functional_requirements().
identify_spacecraft_name()
def pyDRAGONS.design_editing.design_edit_tools.identify_spacecraft_name (design_data)
Identify the spacecraft name from the provided design data.
Parameters:
- design_data (DataFrame): DataFrame containing design data.
Returns:
str: The name of the spacecraft.
This function iterates through the provided design data and identifies the spacecraft name,
which is associated with the classifier 'Spacecraft'.
It performs the following steps:
1. Iterates through each element in the design data.
2. Checks if the element is classified as 'Spacecraft'.
3. Returns the name of the spacecraft when found.
Note:
- The 'design_data' DataFrame should contain information about design elements.
- The 'classifier' column is expected to classify elements.
Example usage:
```
spacecraft_name = identify_spacecraft_name(design_data)
```
References pyDRAGONS.design_editing.design_edit_tools.identify_spacecraft_name().
Referenced by pyDRAGONS.design_editing.design_edit_tools.edit_design_functions(), and pyDRAGONS.design_editing.design_edit_tools.identify_spacecraft_name().
infer_functional_assignments()
def pyDRAGONS.design_editing.design_edit_tools.infer_functional_assignments (design_name, function_data, graph)
Infer functional assignments and add domain labels based on the loaded design model.
Parameters:
- design_name (str): The name of the design.
- function_data (DataFrame): DataFrame containing function data.
- graph: The Neo4j graph object representing the database.
Returns:
None
This function consults the loaded design model to infer functional assignments and add domain labels.
It loops through all functions, identifies related modes, components, and requirements, and assigns domains
as subtypes based on the design model.
It performs the following steps:
1. Reads design data from the provided design name.
2. Constructs a Cypher query to match function, requirement, requirement clause, requirement signal, and design elements.
3. Runs the query against the Neo4j graph to retrieve function-design element pairs.
4. Assigns requirement domains, component domains, and adds inferred assignment labels to the design data.
Note:
- The design data and function data are expected to be saved as CSV files.
- The 'graph' parameter should be a Neo4j graph object representing the database.
- Both design data and ontology data are expected to be saved in the './data/' directory.
Example usage:
```
infer_functional_assignments("DesignA", function_data, graph)
```
References pyDRAGONS.design_editing.design_edit_tools.add_inferred_assigment_labels(), pyDRAGONS.design_editing.design_edit_tools.edit_data_file_function_details(), and pyDRAGONS.design_editing.design_edit_tools.infer_functional_assignments().
Referenced by pyDRAGONS.design_editing.design_edit_tools.infer_functional_assignments().
list_classifiers_of_type()
def pyDRAGONS.design_editing.design_edit_tools.list_classifiers_of_type (classifier_data)
References pyDRAGONS.design_editing.design_edit_tools.list_classifiers_of_type().
Referenced by pyDRAGONS.design_editing.design_edit_tools.list_classifiers_of_type().
list_components()
def pyDRAGONS.design_editing.design_edit_tools.list_components (design_name, graph)
List all requirements from the provided mission data.
Parameters:
Returns:
References pyDRAGONS.design_editing.design_edit_tools.list_components().
Referenced by pyDRAGONS.design_editing.design_edit_tools.list_components().
list_design_elements()
def pyDRAGONS.design_editing.design_edit_tools.list_design_elements (design_data)
References pyDRAGONS.design_editing.design_edit_tools.list_design_elements().
Referenced by pyDRAGONS.design_editing.design_edit_tools.list_design_elements().
list_domain_labels()
def pyDRAGONS.design_editing.design_edit_tools.list_domain_labels (mission_name)
List domain labels for a mission.
Parameters:
- mission_name (str): The name of the mission.
Returns:
None
This function lists domain labels for a given mission.
It reads mission data from an Excel file and extracts domain labels from the 'domain' column.
It performs the following steps:
1. Reads mission data from the provided mission name.
2. Iterates through each row and splits domain labels separated by ';'.
3. Appends unique domain labels to the 'domains' list.
4. Prints the list of domain labels.
Note:
- The mission data is expected to be saved in an Excel file named '{mission_name}_Parsed_Requirement_Info.xlsx'.
Example usage:
```
list_domain_labels("MissionA")
```
References pyDRAGONS.design_editing.design_edit_tools.list_domain_labels().
Referenced by pyDRAGONS.design_editing.design_edit_tools.list_domain_labels().
list_functions()
def pyDRAGONS.design_editing.design_edit_tools.list_functions (design_data)
List all functions from the provided design data.
Parameters:
- design_data (DataFrame): DataFrame containing design data.
Returns:
list: A list of function names.
This function extracts and returns a list of all functions from the provided design data.
It iterates through the 'name' and 'classifier' columns of the design data and appends
the names of elements classified as 'Function' to the 'function_list'.
Note:
- The 'design_data' DataFrame should contain information about design elements.
- The 'classifier' column is expected to classify elements as 'Function' or not.
Example usage:
```
function_list = list_functions(design_data)
```
References pyDRAGONS.design_editing.design_edit_tools.list_functions().
Referenced by pyDRAGONS.design_editing.design_edit_tools.edit_design_functions(), and pyDRAGONS.design_editing.design_edit_tools.list_functions().
list_modes()
def pyDRAGONS.design_editing.design_edit_tools.list_modes (design_data, mode_data)
List all modes from the provided design data based on mode classifiers.
Parameters:
- design_data (DataFrame): DataFrame containing design data.
- mode_data (DataFrame): DataFrame containing mode information.
Returns:
list: A list of tuples containing mode indices and their corresponding names.
This function extracts and returns a list of modes from the provided design data
based on mode classifiers provided in the mode data.
It iterates through the 'name' and 'classifier' columns of the design data and checks
if the element classifier matches any of the mode classifiers provided in the mode data.
If a match is found, it appends a tuple containing the mode index and the element name
to the 'mode_list'.
Note:
- The 'design_data' DataFrame should contain information about design elements.
- The 'classifier' column is expected to classify elements.
- The 'mode_data' DataFrame should contain mode information including mode classifiers.
Example usage:
```
mode_list = list_modes(design_data, mode_data)
```
References pyDRAGONS.design_editing.design_edit_tools.list_modes().
Referenced by pyDRAGONS.design_editing.design_edit_tools.edit_design_functions(), and pyDRAGONS.design_editing.design_edit_tools.list_modes().
list_requirements()
def pyDRAGONS.design_editing.design_edit_tools.list_requirements (mission_name, grab_text, graph)
List all requirements from the provided mission data.
Parameters:
Returns:
References pyDRAGONS.design_editing.design_edit_tools.list_requirements().
Referenced by pyDRAGONS.design_editing.design_edit_tools.list_requirements().
list_sub_class_labels()
def pyDRAGONS.design_editing.design_edit_tools.list_sub_class_labels (design_name)
List sub-class labels for a design.
Parameters:
- design_name (str): The name of the design.
Returns:
None
This function lists sub-class labels for a given design.
It reads design data from a file and extracts sub-class labels from the 'sub_class' column.
It performs the following steps:
1. Reads design data from the provided design name.
2. Iterates through each row and splits sub-class labels separated by ';'.
3. Appends unique sub-class labels to the 'sub_classes' list.
4. Prints the list of sub-class labels.
Note:
- The design data is expected to be saved in a file named '{design_name}_info.csv'.
Example usage:
```
list_sub_class_labels("DesignA")
```
References pyDRAGONS.design_editing.design_edit_tools.list_sub_class_labels().
Referenced by pyDRAGONS.design_editing.design_edit_tools.list_sub_class_labels().
refresh_model_in_data_based()
def pyDRAGONS.design_editing.design_edit_tools.refresh_model_in_data_based (design_name, design_data, mission_name, graph)
References pyDRAGONS.database_interaction.data_extraction.load_mission_requirements(), pyDRAGONS.database_interaction.data_extraction.process_design_data(), and pyDRAGONS.design_editing.design_edit_tools.refresh_model_in_data_based().
Referenced by pyDRAGONS.design_editing.design_edit_tools.refresh_model_in_data_based().
update_data_file_domains()
def pyDRAGONS.design_editing.design_edit_tools.update_data_file_domains (Domain, data, req, mission_name)
Update domain information in the data file.
Parameters:
- Domain (str): The domain information to update.
- data (DataFrame): DataFrame containing data.
- req (str): The requirement ID.
- mission_name (str): The name of the mission.
Returns:
None
This function updates domain information in the provided data file based on the given domain, requirement ID, and mission name.
It performs the following steps:
1. Checks if the provided domain is not 'n'.
2. Adds a 'domain' column to the data if it does not exist.
3. Updates the domain information for the specified requirement if the domain is not already present.
4. Writes the updated data to the mission-specific file.
Note:
- The 'data' DataFrame should contain the data to be updated.
- The 'req' parameter specifies the requirement ID to update.
- The 'mission_name' parameter specifies the name of the mission.
Example usage:
```
update_data_file_domains("DomainA", data, "REQ123", "MissionX")
```
References pyDRAGONS.design_editing.design_edit_tools.update_data_file_domains().
Referenced by pyDRAGONS.design_editing.design_edit_tools.edit_mission_domains(), and pyDRAGONS.design_editing.design_edit_tools.update_data_file_domains().
update_data_file_with_label()
def pyDRAGONS.design_editing.design_edit_tools.update_data_file_with_label (label, data, req, mission_name, colum_name)
Update data file with the given label.
Parameters:
- label (str): The label to update.
- data (list): A list containing DataFrames representing different sheets of the Excel file.
- req (str): The requirement ID.
- mission_name (str): The name of the mission.
- colum_name (str): The name of the column to update.
Returns:
None
This function updates the provided data file with the given label for the specified requirement.
It performs the following steps:
1. Checks if the provided label is not 'n'.
2. Adds a new column with the given name if it does not exist in the first sheet.
3. Updates the label for the specified requirement if it is not already present.
4. Writes the updated data to the mission-specific Excel file with multiple sheets.
Note:
- The 'data' list should contain DataFrames representing different sheets of the Excel file.
- The 'req' parameter specifies the requirement ID to update.
- The 'mission_name' parameter specifies the name of the mission.
- The 'colum_name' parameter specifies the name of the column to update.
Example usage:
```
update_data_file_with_label("LabelA", data, "REQ123", "MissionX", "ColumnA")
```
References pyDRAGONS.design_editing.design_edit_tools.update_data_file_with_label().
Referenced by pyDRAGONS.design_editing.design_edit_tools.edit_mission_functional_requirements(), and pyDRAGONS.design_editing.design_edit_tools.update_data_file_with_label().