NALMAGE: nalmage.diagram_generation Namespace Reference
nalmage.diagram_generation Namespace Reference
Functions
def create_plantuml_diagram (model_file_name)
def xml_to_dict (t)
def check_for_populated_entry (str)
def generate_node_name (element)
def find_true_parent (parent_nodes, i, node_name, edges)
def find_true_child (child_nodes, i, node_name, edges)
def compute_unique_node_names (edges)
def create_tree_from_dict (edges, collected_data, parent=None)
def find_edges (edges, collected_data, parent=None)
def generate_DOT (edges, file_name)
def draw (graph, parent_name, child_name)
def visit (graph, node, parent=None)
def get_edges (edges, treedict, parent=None)
Function Documentation
check_for_populated_entry()
def nalmage.diagram_generation.check_for_populated_entry (str)
References nalmage.diagram_generation.check_for_populated_entry().
Referenced by nalmage.diagram_generation.check_for_populated_entry(), and nalmage.diagram_generation.generate_node_name().
compute_unique_node_names()
def nalmage.diagram_generation.compute_unique_node_names (edges)
References nalmage.diagram_generation.compute_unique_node_names(), nalmage.diagram_generation.find_true_child(), and nalmage.diagram_generation.find_true_parent().
Referenced by nalmage.diagram_generation.compute_unique_node_names().
create_plantuml_diagram()
def nalmage.diagram_generation.create_plantuml_diagram (model_file_name)
References nalmage.diagram_generation.create_plantuml_diagram().
Referenced by nalmage.diagram_generation.create_plantuml_diagram(), nalmage.ner_tools.import_model_from_yaml(), and nalmage.ner_tools.output_model_to_yaml().
create_tree_from_dict()
def nalmage.diagram_generation.create_tree_from_dict (edges, collected_data, parent = None)
References nalmage.diagram_generation.create_tree_from_dict(), and nalmage.diagram_generation.get_edges().
Referenced by nalmage.diagram_generation.create_tree_from_dict().
draw()
def nalmage.diagram_generation.draw (graph, parent_name, child_name)
References nalmage.diagram_generation.draw().
Referenced by nalmage.diagram_generation.draw(), and nalmage.diagram_generation.visit().
find_edges()
def nalmage.diagram_generation.find_edges (edges, collected_data, parent = None)
References nalmage.diagram_generation.find_edges(), and nalmage.diagram_generation.generate_node_name().
Referenced by nalmage.diagram_generation.find_edges().
find_true_child()
def nalmage.diagram_generation.find_true_child (child_nodes, i, node_name, edges)
References nalmage.diagram_generation.find_true_child().
Referenced by nalmage.diagram_generation.compute_unique_node_names(), and nalmage.diagram_generation.find_true_child().
find_true_parent()
def nalmage.diagram_generation.find_true_parent (parent_nodes, i, node_name, edges)
References nalmage.diagram_generation.find_true_parent().
Referenced by nalmage.diagram_generation.compute_unique_node_names(), and nalmage.diagram_generation.find_true_parent().
generate_DOT()
def nalmage.diagram_generation.generate_DOT (edges, file_name)
References format, and nalmage.diagram_generation.generate_DOT().
Referenced by nalmage.diagram_generation.generate_DOT().
generate_node_name()
def nalmage.diagram_generation.generate_node_name (element)
References nalmage.diagram_generation.check_for_populated_entry(), and nalmage.diagram_generation.generate_node_name().
Referenced by nalmage.diagram_generation.find_edges(), and nalmage.diagram_generation.generate_node_name().
get_edges()
def nalmage.diagram_generation.get_edges (edges, treedict, parent = None)
References nalmage.diagram_generation.get_edges().
Referenced by nalmage.diagram_generation.create_tree_from_dict(), and nalmage.diagram_generation.get_edges().
visit()
def nalmage.diagram_generation.visit (graph, node, parent = None)
References nalmage.diagram_generation.draw(), and nalmage.diagram_generation.visit().
Referenced by nalmage.diagram_generation.visit().
xml_to_dict()
def nalmage.diagram_generation.xml_to_dict (t)
References nalmage.diagram_generation.xml_to_dict().
Referenced by nalmage.diagram_generation.xml_to_dict().